#!/usr/bin/env python3
"""
paper1_run_all.py -- the master runner for the reproduction bundle of

    "Interference as the Composition Defect of Stochastic Shadows:
     Records, Gauge, and the Loop Signature of Indivisible Stochastic
     Processes"

It runs every section script in order, regenerates every number the paper
prints, collects the per-section receipts, prints one receipts table, and
exits 0 if and only if every self-anchor passes.

A self-anchor compares a COMPUTED value against the value PRINTED IN THE
PAPER.  Exit 1 happens only on such a mismatch: substantive negatives (the
seven failing support classes, the composite-level witness, the refuted
converse, the recorded-but-phased limit) are results, not failures, and they
exit 0.

    /opt/homebrew/bin/python3.13 paper1_run_all.py            # everything
    /opt/homebrew/bin/python3.13 paper1_run_all.py 2 3 4      # named sections
"""

from __future__ import annotations

import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
PYTHON = sys.executable

SECTIONS = [
    ("2", "sec2_defect_algebra.py", "the three defects and the coherence law"),
    ("3", "sec3_chsh_bodies.py", "the CHSH three-class skeleton"),
    ("4", "sec4_records.py", "records"),
    ("5", "sec5_gauge.py", "the gauge of a compositional law"),
    ("6", "sec6_signature.py", "the loop signature and its incompleteness"),
    ("7", "sec7_descent.py", "record descent and its limit"),
    ("8", "sec8_independence.py", "independence of the obstruction families"),
    ("9", "sec9_ltp.py", "the law-of-total-probability lemma"),
]


def parse_receipts(text):
    """pull the (anchors, pass, fail) line out of a section's output."""
    for line in reversed(text.splitlines()):
        if "anchors," in line and "pass," in line:
            head, tail = line.split(":", 1)
            parts = tail.split(",")
            n = int(parts[0].strip().split()[0])
            p = int(parts[1].strip().split()[0])
            f = int(parts[2].strip().split()[0])
            return head.strip(), n, p, f
    return None, 0, 0, 0


def main():
    want = set(sys.argv[1:]) or {s[0] for s in SECTIONS}
    t0 = time.time()
    rows = []
    failed_sections = []
    print("=" * 74)
    print("REPRODUCTION BUNDLE -- Interference as the Composition Defect of")
    print("                       Stochastic Shadows")
    print("=" * 74)
    print("interpreter : %s" % PYTHON)
    print("directory   : %s" % HERE)
    print("sections    : %s" % " ".join(sorted(want)))
    print("=" * 74)
    for tag, script, title in SECTIONS:
        if tag not in want:
            continue
        print()
        print("### Section %s -- %s" % (tag, title))
        sys.stdout.flush()
        t1 = time.time()
        proc = subprocess.run([PYTHON, "-u", os.path.join(HERE, script)],
                              capture_output=True, text=True, cwd=HERE)
        dt = time.time() - t1
        sys.stdout.write(proc.stdout)
        if proc.stderr.strip():
            sys.stdout.write(proc.stderr)
        name, n, p, f = parse_receipts(proc.stdout)
        rows.append((tag, script, n, p, f, dt, proc.returncode))
        if proc.returncode != 0 or f:
            failed_sections.append(tag)
        sys.stdout.flush()

    print()
    print("=" * 74)
    print("RECEIPTS TABLE")
    print("=" * 74)
    print("  %-4s %-28s %8s %7s %7s %9s %6s"
          % ("sec", "script", "anchors", "pass", "fail", "seconds", "exit"))
    print("  " + "-" * 70)
    tot_a = tot_p = tot_f = 0
    for tag, script, n, p, f, dt, rc in rows:
        print("  %-4s %-28s %8d %7d %7d %9.1f %6d"
              % (tag, script, n, p, f, dt, rc))
        tot_a += n
        tot_p += p
        tot_f += f
    print("  " + "-" * 70)
    print("  %-4s %-28s %8d %7d %7d %9.1f"
          % ("all", "", tot_a, tot_p, tot_f, time.time() - t0))
    print("=" * 74)
    if failed_sections:
        print("SELF-ANCHOR FAILURE in section(s): %s" % ", ".join(failed_sections))
        print("A computed number disagrees with the number printed in the paper.")
        sys.exit(1)
    print("ALL SELF-ANCHORS PASS: every number printed in the paper is")
    print("regenerated by this bundle in exact arithmetic.")
    sys.exit(0)


if __name__ == "__main__":
    main()
