#!/usr/bin/env python3
"""
clock_test_tool.py - a structural test for finite-state noise-model
compatibility, run on real surface-code syndrome data.

THE TEST.  For a stationary binary stream s_t (one stabilizer's
detection events over QEC rounds), estimate the run statistics
p(1^n) = Pr[s_t = ... = s_{t+n-1} = 1] and form the Hankel matrix
H[i, j] = p(1^(i+j)), 0 <= i, j <= m.  If the stream is generated by
ANY finite hidden-Markov environment (of any dimension), H is positive
semidefinite (the diagonal sequence is a Hamburger moment sequence:
the letter-transfer operator of a nonnegative realization has real
spectrum).  A statistically SIGNED H therefore certifies that no
finite-state noise model of any size reproduces the stream - a
structural, not parametric, conclusion.

ROBUSTNESS PROPERTY (important for real data): a convex mixture of
moment sequences is a moment sequence, so shot-to-shot drift or
parameter wander CANNOT sign the Hankel - pooling over shots is safe,
and only genuinely oscillatory (complex-spectrum) environment
structure can produce a violation.

STATISTICS.  lambda_min(H_hat) with a block bootstrap over SHOTS
(B resamples); verdict SIGNED only if the upper 97.5% bootstrap bound
is < 0; PASS (moment-compatible) otherwise.

DATA.  Google's 2023 surface-code memory experiment (Zenodo 6804040):
detection_events.b8 (stim b8 packing) + DETECTOR(x, y, t) coordinates
parsed from circuit_noisy.stim.  Bulk rounds only (edge rounds carry
boundary effects).

CONTROLS.  (+) a synthetic oscillatory environment (an irrational-
rotation modulator) at matched event rate MUST fail the test - the
instrument's positive control; (-) an i.i.d. stream at matched rate
must pass.
"""
import numpy as np
import os, re, sys

rng = np.random.default_rng(2023)

# ---------------- parsing ----------------
def parse_detectors(stim_path):
    coords = []
    with open(stim_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("DETECTOR("):
                m = re.match(r"DETECTOR\(([^)]*)\)", line)
                vals = [float(v) for v in m.group(1).split(",")]
                coords.append(tuple(vals))
    return coords      # (x, y, t) in detector-index order

def load_b8(path, num_detectors):
    nbytes = (num_detectors + 7) // 8
    raw = np.fromfile(path, dtype=np.uint8).reshape(-1, nbytes)
    bits = np.unpackbits(raw, axis=1, bitorder="little")
    return bits[:, :num_detectors]

def stabilizer_series(folder):
    coords = parse_detectors(os.path.join(folder, "circuit_noisy.stim"))
    D = len(coords)
    ev = load_b8(os.path.join(folder, "detection_events.b8"), D)
    groups = {}
    for idx, (x, y, t) in enumerate(coords):
        groups.setdefault((x, y), []).append((t, idx))
    series = {}
    for key, lst in groups.items():
        lst.sort()
        ts = [t for t, i in lst]
        idxs = [i for t, i in lst]
        series[key] = (np.array(ts), ev[:, idxs])   # shots x rounds
    return series

# ---------------- the test ----------------
def run_stats(S, m):
    """p_hat(1^n), n = 0..2m, from shots x T binary matrix S, using
    all start positions (windowed run estimator)."""
    shots, T = S.shape
    p = [1.0]
    run = np.ones_like(S)
    acc = S.copy()
    for n in range(1, 2 * m + 1):
        if n > 1:
            acc = acc[:, :-1] & S[:, n - 1:]
        p.append(acc.mean())
    return np.array(p, float)

def hankel_min(p, m):
    H = np.array([[p[i + j] for j in range(m + 1)] for i in range(m + 1)])
    return np.linalg.eigvalsh(H)[0]

def clock_test(S, m=3, B=200):
    """Basic-bootstrap CI for the TRUE lambda_min.  Degenerate (exactly
    singular) Hankels - e.g. iid streams, where p(1^n) = p^n is rank
    one - make the plug-in estimate biased negative; the basic
    bootstrap CI_true = [2 lam_hat - q_hi, 2 lam_hat - q_lo] corrects
    the bias.  Verdict SIGNED only if the corrected upper bound < 0."""
    shots = S.shape[0]
    p = run_stats(S, m)
    lam = hankel_min(p, m)
    boot = []
    for _ in range(B):
        pick = rng.integers(0, shots, shots)
        pb = run_stats(S[pick], m)
        boot.append(hankel_min(pb, m))
    boot = np.sort(np.array(boot))
    q_lo, q_hi = boot[int(0.025 * B)], boot[int(0.975 * B) - 1]
    lo, hi = 2 * lam - q_hi, 2 * lam - q_lo
    verdict = "SIGNED (no finite-state model)" if hi < 0 else \
        "PASS (moment-compatible)"
    return p, lam, (lo, hi), verdict

# ---------------- main ----------------
def analyze_folder(folder, m=3, bulk=(2, None)):
    name = os.path.basename(folder)
    series = stabilizer_series(folder)
    print(f"\n--- {name}: {len(series)} stabilizers ---")
    results = []
    for key in sorted(series):
        ts, S = series[key]
        # bulk rounds only
        tmax = ts.max()
        mask = (ts >= bulk[0]) & (ts <= tmax - 2)
        S = S[:, mask]
        if S.shape[1] < 2 * m + 2:
            continue
        rate = S.mean()
        drift = np.abs(S.mean(axis=0) - rate).max()
        p, lam, (lo, hi), verdict = clock_test(S, m=m)
        results.append((key, rate, lam, lo, hi, verdict))
        print(f"  stab {key}: rate {rate:.4f}  round-drift {drift:.4f}"
              f"  lam_min {lam:+.2e}  CI [{lo:+.2e}, {hi:+.2e}]"
              f"  -> {verdict}")
    return results

if __name__ == "__main__":
    base = "/tmp/qec_data"
    folders = [f for f in sorted(os.listdir(base))
               if "r25" in f and os.path.isdir(os.path.join(base, f))]
    print("== THE CLOCK TEST ON REAL SURFACE-CODE SYNDROME DATA ==")
    print("   (Google 2023 memory experiment, Zenodo 6804040;")
    print("    50,000 shots per folder; bulk rounds; m = 3 Hankel)")
    all_res = []
    for f in folders[:6]:
        all_res += analyze_folder(os.path.join(base, f))

    n_pass = sum(1 for r in all_res if "PASS" in r[5])
    n_sign = len(all_res) - n_pass
    print(f"\n== AGGREGATE: {n_pass} PASS, {n_sign} SIGNED of"
          f" {len(all_res)} stabilizer streams ==")

    # ---------------- controls ----------------
    print("\n== controls ==")
    # (-) i.i.d. at matched rate
    rate = np.mean([r[1] for r in all_res]) if all_res else 0.12
    S_iid = (rng.uniform(size=(50000, 22)) < rate).astype(np.uint8)
    p, lam, (lo, hi), verdict = clock_test(S_iid, m=3)
    print(f"  iid control (rate {rate:.3f}):       lam_min {lam:+.2e}"
          f"  CI [{lo:+.2e}, {hi:+.2e}]  -> {verdict}")
    # (+) oscillatory (irrational-rotation) environment, matched rate
    th = 1.0
    phase0 = rng.uniform(0, 2 * np.pi, size=(50000, 1))
    tgrid = np.arange(22)[None, :]
    prob = rate * (1 + 0.9 * np.cos(phase0 + th * tgrid))
    S_osc = (rng.uniform(size=(50000, 22)) < prob).astype(np.uint8)
    p, lam, (lo, hi), verdict = clock_test(S_osc, m=3)
    print(f"  oscillatory control (same rate):    lam_min {lam:+.2e}"
          f"  CI [{lo:+.2e}, {hi:+.2e}]  -> {verdict}")
    print("\n  (the instrument: a hidden irrational rotation SIGNS the")
    print("   Hankel at matched rate and statistics, while iid passes -")
    print("   whatever the device data shows is therefore a statement")
    print("   about the device, not about the test's power)")
