#!/usr/bin/env python3
"""
Paper 43 §7.1 -- Phase 0: pin the target modular space for Lemma 1(b).

The 't Hooft modular action on Z_2 x Z_2 fluxes (e,m) is (mod 2):
    S: (e,m) -> (m, -e) = (m, e)        [electric <-> magnetic swap]
    T: (e,m) -> (e, m + e)
acting on the 4-dim flux space V = {f : Z_2 x Z_2 -> C}. We compute the SL(2,Z) representation these
generate, verify the group relations, identify the congruence subgroup Gamma that acts trivially
(=> the partition vector is a modular form for Gamma), and decompose the representation. This pins the
finite-dimensional target space the conjecture's part (a) lives in.
"""
import numpy as np
import itertools

# flux states (e,m): index 0..3
states = [(0, 0), (0, 1), (1, 0), (1, 1)]
idx = {s: i for i, s in enumerate(states)}


def perm_matrix(action):
    """4x4 permutation matrix M with M[a, b] = 1 if action(state_b) = state_a (push-forward on f)."""
    M = np.zeros((4, 4), dtype=int)
    for b, s in enumerate(states):
        a = idx[action(s)]
        M[a, b] = 1
    return M


S = perm_matrix(lambda em: (em[1], em[0]))                       # (e,m)->(m,e)
T = perm_matrix(lambda em: (em[0], (em[1] + em[0]) % 2))         # (e,m)->(e,m+e)
I = np.eye(4, dtype=int)


def matpow(M, k):
    R = I.copy()
    for _ in range(k):
        R = R @ M
    return R


def generate_group(gens):
    seen = {tuple(I.flatten())}
    frontier = [I]
    elems = [I]
    while frontier:
        nf = []
        for g in frontier:
            for h in gens:
                gh = g @ h
                key = tuple(gh.flatten())
                if key not in seen:
                    seen.add(key); nf.append(gh); elems.append(gh)
        frontier = nf
    return elems


if __name__ == "__main__":
    print("=" * 76)
    print("Paper 43 §7.1 / Phase 0: SL(2,Z) representation on the Z_2xZ_2 flux space")
    print("=" * 76 + "\n")

    print("S (e<->m swap) as a permutation of states", states, ":")
    print("   ", [states[int(np.argmax(S[:, b]))] for b in range(4)])
    print("T (m->m+e):")
    print("   ", [states[int(np.argmax(T[:, b]))] for b in range(4)], "\n")

    # group relations (SL(2,Z): S^4=I, (ST)^3=S^2; on Z_2 flux -I acts trivially so S^2=I)
    print("Modular relations on the flux representation:")
    print(f"   S^2 = I ? {np.array_equal(matpow(S,2), I)}    (-I acts trivially on Z_2 flux)")
    print(f"   T^2 = I ? {np.array_equal(matpow(T,2), I)}    (T^2 in Gamma(2))")
    print(f"   (ST)^3 = I ? {np.array_equal(matpow(S@T,3), I)}")
    G = generate_group([S, T])
    print(f"   |group generated by S,T| = {len(G)}   (S_3 = SL(2,Z_2) has order 6)\n")

    # decomposition: which states are fixed / permuted
    fixed = [s for s in states if idx[s] == int(np.argmax(S[:, idx[s]])) == int(np.argmax(T[:, idx[s]]))]
    print("Representation structure:")
    print(f"   trivial flux (0,0) is a SINGLET (fixed by S and T).")
    print(f"   the 3 nontrivial fluxes {{(0,1),(1,0),(1,1)}} = {{magnetic, electric, dyonic}}")
    print(f"   are PERMUTED by S_3  (S=(e<->m) swaps (0,1)<->(1,0); T swaps (1,0)<->(1,1)).")
    # character of the 3-dim nontrivial block = perm rep of S_3 = trivial + standard(2d)
    print(f"   => V = 2*(trivial) + standard(2-dim)  as S_3-reps.\n")

    print("CONCLUSION (Phase 0):")
    print(" - The SL(2,Z) action on the flux vector factors through SL(2,Z)/Gamma(2) = SL(2,Z_2) = S_3.")
    print("   Hence Gamma(2) (level-2 principal congruence subgroup) acts trivially: the flux partition")
    print("   vector is a (vector-valued) modular form for GAMMA(2), with S_3 permuting the 3 nontrivial")
    print("   flux sectors -- the SAME structure as the Jacobi thetas {theta2,theta3,theta4}.")
    print(" - Target space: weakly-holomorphic vector-valued modular forms for Gamma(2) (poles allowed at")
    print("   cusps = the area-law growth e^{sigma A}=q^{-#}), multiplier rho = the S_3 flux permutation.")
    print(" - Candidate weight: w=1/2 in 2D (realized exactly by {theta2,theta3,theta4}); w=-(d-2)/2=-1 in")
    print("   4D from the effective-string eta^{-(d-2)} (worldsheet variable).")
    print(" - This space is FINITE-DIMENSIONAL per weight (ring of Gamma(2) forms = C[theta3^4,theta4^4]),")
    print("   i.e. the rigidity the conjecture needs. Whether the 4D Z actually lands in it is Phase 1.")
