"""
v6 Paper 2 Part II §5.37: invariant-law guess search.

The previous audit says that known construction classes fail unless the full
four-role Gram is supplied.  This script asks a sharper first-principles
question:

    What invariant scalar law could make record, source, causal, and
    antichain-density roles four derivatives of the same fact?

The surviving guess is an invariant deletion action:

    A_x = log dP(local collar with x retained) / dP(local collar with x deleted)

or equivalently a finite relative-entropy/modular deletion increment.  If the
four roles are generated by invariant deformations of this one scalar action,
then the role Gram is its local Fisher/Hessian matrix.  That is a real Branch-A
target; it is not proved here for the actual interacting ISP law.
"""

from __future__ import annotations

from dataclasses import dataclass

from v6_p2r_full_role_gram_derivation import (
    ROLE_ORDER,
    LawInstance,
    base_role_rows,
    beta_from_gram,
    gram,
    matrix_span,
    role_rows,
)


@dataclass
class Guess:
    name: str
    invariant_scalar: bool
    deletion_atom: bool
    record: bool
    source: bool
    causal: bool
    antichain: bool
    same_functional: bool
    local_microcausal: str
    beta_status: str
    verdict: str


@dataclass
class HessianAudit:
    candidate: str
    full_roles: bool
    same_scalar: bool
    acv: bool
    j_span: float
    kappa_min: float
    beta_span: float
    verdict: str


def stable_full_hessians() -> list[list[list[float]]]:
    out = []
    for step in [1.0, 0.5, 0.25, 0.0]:
        rows = {
            "record": [0.95 + 0.02 * step, 0.05, 0.02, 0.00],
            "source": [0.08, 0.92 + 0.03 * step, 0.05, 0.02],
            "causal": [0.03, 0.06, 0.96 + 0.01 * step, 0.04],
            "antichain": [0.02, 0.04, 0.08, 0.98 + 0.01 * step],
        }
        out.append(gram(role_rows(LawInstance(rows, "pre"), ROLE_ORDER)))
    return out


def no_source_hessians() -> list[list[list[float]]]:
    out = []
    for strength in [0.55, 0.75, 0.95, 1.15]:
        rows = base_role_rows(strength)
        out.append(gram(role_rows(LawInstance(rows, "pre"), ROLE_ORDER)))
    return out


def audit_hessian(
    candidate: str,
    hessians: list[list[list[float]]],
    full_roles: bool,
    same_scalar: bool,
) -> HessianAudit:
    kappas = []
    betas = []
    oks = []
    if full_roles and same_scalar:
        for hessian in hessians:
            kappa, beta, ok = beta_from_gram(hessian, 0.015)
            kappas.append(kappa)
            betas.append(beta)
            oks.append(ok)

    acv = all(oks) if oks else False
    j_span = matrix_span(hessians) if hessians else float("inf")
    kappa_min = min(kappas) if kappas else 0.0
    beta_span = max(betas) - min(betas) if betas else float("inf")
    passes = (
        full_roles
        and same_scalar
        and acv
        and kappa_min > 0.0
        and beta_span <= 0.02
        and j_span <= 0.07
    )
    return HessianAudit(
        candidate=candidate,
        full_roles=full_roles,
        same_scalar=same_scalar,
        acv=acv,
        j_span=j_span,
        kappa_min=kappa_min,
        beta_span=beta_span,
        verdict="PASS-TARGET" if passes else "FAIL",
    )


def guesses() -> list[Guess]:
    return [
        Guess(
            "local scalar threshold",
            True,
            False,
            True,
            True,
            False,
            False,
            False,
            "yes",
            "free beta",
            "FAIL",
        ),
        Guess(
            "stress/RCE response",
            True,
            False,
            False,
            True,
            False,
            False,
            False,
            "yes",
            "external geometry",
            "FAIL",
        ),
        Guess(
            "causal-set atom",
            True,
            True,
            False,
            False,
            True,
            True,
            False,
            "yes",
            "source absent",
            "FAIL",
        ),
        Guess(
            "entanglement equilibrium diamond",
            True,
            False,
            False,
            True,
            True,
            True,
            True,
            "local only in first-law limit",
            "record event absent",
            "NEAR-MISS",
        ),
        Guess(
            "null modular/QNEC atom",
            True,
            False,
            True,
            True,
            True,
            True,
            True,
            "null/Rindler-local, not generic",
            "conditional",
            "NEAR-MISS",
        ),
        Guess(
            "invariant deletion action",
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            "assumed theorem target",
            "derived from Hessian",
            "PASS-TARGET",
        ),
    ]


def fmt(value: float) -> str:
    return "inf" if value == float("inf") else f"{value:.4f}"


def yn(flag: bool) -> str:
    return "yes" if flag else "no"


def print_guesses(rows: list[Guess]) -> None:
    print("first-principles guess audit")
    print("----------------------------")
    print(
        "candidate                       scalar  delete  rec  src  caus  anti  "
        "sameF  locality                    beta/status       verdict"
    )
    for row in rows:
        print(
            f"{row.name:31s}  "
            f"{yn(row.invariant_scalar):6s}  "
            f"{yn(row.deletion_atom):6s}  "
            f"{yn(row.record):3s}  "
            f"{yn(row.source):3s}  "
            f"{yn(row.causal):4s}  "
            f"{yn(row.antichain):4s}  "
            f"{yn(row.same_functional):5s}  "
            f"{row.local_microcausal:26s}  "
            f"{row.beta_status:16s}  "
            f"{row.verdict}"
        )
    print()


def print_hessian_audits(rows: list[HessianAudit]) -> None:
    print("single-scalar Hessian audit")
    print("---------------------------")
    print(
        "candidate                       roles  sameF  ACV   J_span  "
        "kappa_min  beta_span  verdict"
    )
    for row in rows:
        print(
            f"{row.candidate:31s}  "
            f"{yn(row.full_roles):5s}  "
            f"{yn(row.same_scalar):5s}  "
            f"{('PASS' if row.acv else 'FAIL'):4s}  "
            f"{fmt(row.j_span):>7s}  "
            f"{row.kappa_min:9.4f}  "
            f"{fmt(row.beta_span):>9s}  "
            f"{row.verdict}"
        )
    print()


def main() -> None:
    hessian_rows = [
        audit_hessian(
            "invariant deletion action",
            stable_full_hessians(),
            full_roles=True,
            same_scalar=True,
        ),
        audit_hessian(
            "source-free scalar action",
            no_source_hessians(),
            full_roles=False,
            same_scalar=True,
        ),
        audit_hessian(
            "assembled four-ledger action",
            stable_full_hessians(),
            full_roles=True,
            same_scalar=False,
        ),
    ]

    print("=" * 104)
    print("v6 Paper 2 Part II §5.37: invariant-law guess search")
    print("=" * 104)
    print_guesses(guesses())
    print_hessian_audits(hessian_rows)
    print("SURVIVING GUESS")
    print("----------------")
    print("The only non-tautological form that can make the four roles one fact is")
    print("an invariant deletion action: a local log Radon-Nikodym/relative-entropy")
    print("increment for retaining rather than deleting one event in its causal")
    print("collar.  Record, source, causal, and antichain roles must be invariant")
    print("deformation derivatives of that single scalar.  The full role Gram is")
    print("then its Fisher/Hessian matrix.  This is a theorem target, not a proof")
    print("that the actual interacting ISP law has the required deletion action.")


if __name__ == "__main__":
    main()
