"""
v6 Paper 3 section 45: sealed finite count-functor origin campaign.

Question:
    Does a closed sealed causal record diamond intrinsically supply the full
    sealed finite count functor: atoms, role-blind count reference, and
    canonical cofinal refinement maps?

Finite answer:
    A single sealed diamond does not.  A finite Boolean record algebra gives
    intrinsic atoms, but endpoint diamonds alone do not determine refinement
    maps, and role marginals do not determine a one-event role identity.

    The positive theorem is conditional and sharper: if the physical base is
    a sealed finite record-algebra functor, with finite Boolean algebras on
    diamonds and intrinsic restriction maps for nested diamonds, then:

      * atoms are the minimal nonzero elements of the Boolean algebra;
      * refinement maps are induced by restriction of atoms;
      * role readouts are internal maps from the same atoms;
      * count/reference measure is stable under regular covers, or more
        generally under a projective fiber-count measure.

    If the record algebra, restriction maps, regular/projective refinement
    rule, or common role maps are supplied externally, the construction is
    branch B.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product


Vector = list[float]


@dataclass(frozen=True)
class CountFunctorAudit:
    target: str
    data: str
    invariant: str
    positive: str
    obstruction: str
    value: str
    verdict: str


def l1(left: Vector, right: Vector) -> float:
    return sum(abs(a - b) for a, b in zip(left, right))


def uniform(n: int) -> Vector:
    return [1.0 / n] * n


def atoms_from_partition(partition: tuple[tuple[int, ...], ...]) -> tuple[tuple[int, ...], ...]:
    # In a finite Boolean algebra generated by a partition, the atoms are the
    # minimal nonempty blocks of the partition.
    return tuple(tuple(block) for block in partition if block)


def hidden_microstate_gap(partition: tuple[tuple[int, ...], ...]) -> int:
    # If only the coarse record algebra is supplied, all microstates inside
    # each block are invisible.  This is the number of extra points hidden
    # behind the algebra atoms in the displayed finite completion.
    return sum(len(block) for block in partition) - len(atoms_from_partition(partition))


def onto_maps(fine_count: int, coarse_count: int) -> list[tuple[int, ...]]:
    maps: list[tuple[int, ...]] = []
    for mapping in product(range(coarse_count), repeat=fine_count):
        if set(mapping) == set(range(coarse_count)):
            maps.append(tuple(mapping))
    return maps


def fiber_profile(mapping: tuple[int, ...], coarse_count: int) -> tuple[int, ...]:
    return tuple(sum(1 for value in mapping if value == i) for i in range(coarse_count))


def push_uniform(mapping: tuple[int, ...], coarse_count: int) -> Vector:
    mass = [0.0] * coarse_count
    fine_mass = 1.0 / len(mapping)
    for target in mapping:
        mass[target] += fine_mass
    return mass


def endpoint_refinement_span(fine_count: int = 4, coarse_count: int = 2) -> float:
    pushed = [push_uniform(mapping, coarse_count) for mapping in onto_maps(fine_count, coarse_count)]
    return max(l1(left, right) for left in pushed for right in pushed)


def count_regular_maps(fine_count: int = 4, coarse_count: int = 2) -> int:
    maps = onto_maps(fine_count, coarse_count)
    return sum(
        1
        for mapping in maps
        if len(set(fiber_profile(mapping, coarse_count))) == 1
    )


def regular_refinement_error() -> float:
    mapping = (0, 0, 1, 1)
    return l1(push_uniform(mapping, 2), uniform(2))


def irregular_refinement_drift() -> float:
    mapping = (0, 0, 0, 1)
    return l1(push_uniform(mapping, 2), uniform(2))


def projective_fiber_measure(mapping: tuple[int, ...], coarse_mass: Vector) -> Vector:
    profile = fiber_profile(mapping, len(coarse_mass))
    fine = [0.0] * len(mapping)
    for fine_index, coarse_index in enumerate(mapping):
        fine[fine_index] = coarse_mass[coarse_index] / profile[coarse_index]
    return fine


def projective_push_error() -> float:
    mapping = (0, 0, 0, 1)
    coarse = uniform(2)
    fine = projective_fiber_measure(mapping, coarse)
    pushed = [0.0, 0.0]
    for fine_index, coarse_index in enumerate(mapping):
        pushed[coarse_index] += fine[fine_index]
    return l1(pushed, coarse)


def projective_nonuniformity() -> float:
    mapping = (0, 0, 0, 1)
    fine = projective_fiber_measure(mapping, uniform(2))
    return l1(fine, uniform(4))


def role_marginal_counterexample() -> float:
    # Same record and source marginals, different one-event identity.
    aligned_joint = [[0.5, 0.0], [0.0, 0.5]]
    crossed_joint = [[0.25, 0.25], [0.25, 0.25]]
    return sum(abs(aligned_joint[i][j] - crossed_joint[i][j]) for i in range(2) for j in range(2))


def common_atom_role_error() -> float:
    # If record and source readouts are maps from the same atoms, the aligned
    # one-event support is an identity, not a matching of two separate marginals.
    record = (0, 0, 1, 1)
    source = (0, 0, 1, 1)
    return sum(1 for r, s in zip(record, source) if r != s)


def audits() -> list[CountFunctorAudit]:
    partition = ((0, 1), (2, 3, 4), (5,))
    coarse = 2
    fine = 4
    onto = onto_maps(fine, coarse)
    return [
        CountFunctorAudit(
            "record algebra atoms",
            "finite Boolean algebra",
            "minimal nonzero elements",
            f"atoms={len(atoms_from_partition(partition))}",
            "requires full record algebra",
            "lattice-intrinsic",
            "PASS-ATOMS-IN-ALGEBRA",
        ),
        CountFunctorAudit(
            "coarse records only",
            "partition blocks",
            "observable algebra atoms",
            f"algebra atoms={len(atoms_from_partition(partition))}",
            f"hidden micro gap={hidden_microstate_gap(partition)}",
            "micro-atoms not seen",
            "FAIL-COARSE-NOT-FULL",
        ),
        CountFunctorAudit(
            "endpoint refinements",
            "4 fine, 2 coarse atoms",
            "surjective maps",
            f"onto maps={len(onto)}",
            "endpoint data do not select",
            f"push span={endpoint_refinement_span():.3f}",
            "FAIL-ENDPOINTS-NOT-MAP",
        ),
        CountFunctorAudit(
            "restriction functor",
            "nested Boolean algebras",
            "atom restriction",
            "fine atom has unique parent",
            "requires inclusion map",
            "canonical if functor given",
            "PASS-MAP-FROM-FUNCTOR",
        ),
        CountFunctorAudit(
            "regular cover",
            "2/2 fiber split",
            "uniform pushforward",
            f"error={regular_refinement_error():.1e}",
            f"regular maps={count_regular_maps()} of {len(onto)}",
            "count stable",
            "PASS-REGULAR-COUNT",
        ),
        CountFunctorAudit(
            "irregular cover",
            "3/1 fiber split",
            "uniform fine atoms",
            f"drift={irregular_refinement_drift():.3f}",
            "global count not stable",
            "needs fiber measure",
            "FAIL-IRREGULAR-GLOBAL-U",
        ),
        CountFunctorAudit(
            "projective fiber count",
            "3/1 split with parent mass",
            "equal split in each fiber",
            f"push error={projective_push_error():.1e}",
            f"nonuniformity={projective_nonuniformity():.3f}",
            "stable if parent map intrinsic",
            "PASS-CONDITIONAL-FIBER-COUNT",
        ),
        CountFunctorAudit(
            "role marginals",
            "record/source counts",
            "same marginal laws",
            "marginals match",
            f"joint span={role_marginal_counterexample():.3f}",
            "one-event identity not fixed",
            "FAIL-MARGINAL-ROLES",
        ),
        CountFunctorAudit(
            "common role atoms",
            "one Boolean algebra",
            "role maps share atoms",
            f"mismatch={common_atom_role_error():.0f}",
            "requires common algebra",
            "role identity internal",
            "PASS-ROLE-MAPS-FROM-ALGEBRA",
        ),
        CountFunctorAudit(
            "single diamond",
            "one closed algebra",
            "no cofinal maps",
            "atoms yes",
            "refinement/action scale no",
            "cannot be enough",
            "NO-GO-SINGLE-DIAMOND",
        ),
        CountFunctorAudit(
            "count-functor theorem",
            "record-algebra functor",
            "atoms+restrictions+fiber count",
            "all maps internal",
            "physical existence open",
            "branch-A base candidate",
            "THM-CONDITIONAL-COUNT-FUNCTOR",
        ),
    ]


def print_audits(rows: list[CountFunctorAudit]) -> None:
    print("sealed finite count-functor origin campaign")
    print("-------------------------------------------")
    print(
        "target                    data                    invariant               "
        "positive                         obstruction                     value                         verdict"
    )
    for row in rows:
        print(
            f"{row.target:25s} "
            f"{row.data:23s} "
            f"{row.invariant:23s} "
            f"{row.positive:32s} "
            f"{row.obstruction:31s} "
            f"{row.value:29s} "
            f"{row.verdict}"
        )


def main() -> None:
    print("=" * 150)
    print("v6 Paper 3 section 45: sealed finite count-functor origin campaign")
    print("=" * 150)
    print_audits(audits())
    print()
    print("VERDICT")
    print("-------")
    print("A single sealed diamond can derive atoms only relative to its full finite")
    print("record algebra.  It cannot derive cofinal refinement maps or role identity")
    print("from endpoint counts or role marginals alone.  Same endpoint diamonds admit")
    print("many inequivalent refinement maps, and same role marginals admit different")
    print("one-event identifications.")
    print()
    print("The positive object is therefore a sealed finite record-algebra functor:")
    print("finite Boolean record algebras on diamonds, intrinsic restriction maps for")
    print("nested diamonds, and a regular or projective fiber-count measure.  From")
    print("that functor, atoms, refinement maps, role-blind U, and the count reference")
    print("are derived.  If the functor is not physical, branch A-current is not closed.")


if __name__ == "__main__":
    main()
