"""
HARDEST adversarial sub-test: the DIMENSIONAL-TRANSMUTATION escape.

Objection a hostile reviewer raises against 'the records' only inverse length is
1/l': the record dynamics can generate a SECOND length, a correlation length xi
(mass gap, RG-invariant scale).  Could xi, or the pair (l, xi), supply a
record-INTRINSIC weight-(-2) value for Lambda0 that is NOT 'just l' ?

Key fact to test: under the gauge l -> mu l, EVERY dynamically generated length
scales the SAME way (it is built by the dimensionless record dynamics times a
power of the lattice unit l).  So xi = f(couplings) * l, with f weight-0.  Then:
  - xi/l = f  is weight-0 (intrinsic, fine - a pure number),
  - but xi ITSELF is weight +1, = (number)*l : still 'one record length',
  - any weight-(-2) combination xi^a l^b with a+b = -2 is (number)*l^{-2}:
    STILL the gauge modulus to the -2 power.
So transmutation gives new weight-0 NUMBERS, never a new weight-charged UNIT.
We prove this and show Lambda0 cannot escape.

Also: verify the Sakharov-induced coefficient G*Lambda_UV^2 = (number)/N is a
pure-number * 1/N relation (the cutoff Lambda_UV CANCELS the way the corpus
claims), and that the de Sitter N_dS is consistent with observed (G,Lambda0).
"""

import sympy as sp
import mpmath as mp

print("="*72)
print("DIMENSIONAL-TRANSMUTATION ESCAPE TEST")
print("="*72)

mu, l, f = sp.symbols('mu l f', positive=True)   # f = dimensionless RG function (weight 0)
# correlation length generated by the dynamics:
xi = f * l            # weight(xi) = weight(f) + weight(l) = 0 + 1 = +1

# Under gauge l -> mu*l:  f is intrinsic (weight 0) so f -> f ; l -> mu*l
xi_gauged = f * (mu*l)
print(f"\n xi = f*l   (f weight 0, RG-invariant number; l weight 1)")
print(f" under l->mu*l :  xi -> {xi_gauged} = mu * xi   (weight +1, confirmed)")

# Try to build ANY weight-(-2) quantity from {l, xi, and weight-0 numbers}:
a, b = sp.symbols('a b')
# general monomial  xi^a * l^b * (number) has length-weight a + b
# require a+b = -2 :
gen = xi**a * l**b
weight_gen = a*1 + b*1   # since both xi and l have weight +1
print(f"\n general monomial xi^a * l^b has weight a+b = {weight_gen}")
print(f" require weight -2 => a+b = -2.  Substitute xi=f*l:")
gen_sub = sp.simplify(xi**a * l**b)   # = f^a * l^(a+b)
print(f"   xi^a l^b = f^a * l^(a+b) = f^a * l^(-2)   when a+b=-2")
print(f"   => ANY weight-(-2) record monomial = (weight-0 number f^a) * l^(-2)")
print(f"   => it is STILL the gauge modulus l to the power -2. NO escape.")

# Hence: Lambda0 = (record number) * l^(-2) is the MOST GENERAL record-built
# weight-(-2) object. The 'record number' can be transmuted/fancy, but the
# l^(-2) is mandatory and l is pure gauge => the VALUE is gauge-dependent =>
# NOT intrinsic.  This is paper57 sec 2.2 proven at the monomial level.
print("\n CONCLUSION: Lambda0_record = (any weight-0 number) * l^(-2).")
print("   The number is fixable (intrinsic); l^(-2) is pure gauge (Theorem G).")
print("   => the no-go is HARDENED, not leaked, by transmutation.")

# ----------------------------------------------------------------------
# Sakharov induced-gravity coefficient: does Lambda_UV cancel?
# Induced 1/(16 pi G) = (1/12) * (1/(4pi)^2) * N_dof * Lambda_UV^2  (schematic
# heat-kernel a_2).  And induced rho_vac ~ Lambda_UV^4.  So:
#   Lambda0 = 8 pi G rho_vac  and  1/G ~ N Lambda_UV^2
#   => Lambda0 ~ (Lambda_UV^4)/(N Lambda_UV^2) = Lambda_UV^2 / N
#   => G * Lambda0 ~ Lambda_UV^4/(N^2 Lambda_UV^2)... track exact powers:
# ----------------------------------------------------------------------
print("\n" + "="*72)
print("SAKHAROV-INDUCED:  does the cutoff Lambda_UV cancel in G*Lambda^2 ?")
print("="*72)
G, N, LamUV, cnum = sp.symbols('G N Lambda_UV c_num', positive=True)
# induced Newton constant: 1/G = alpha * N * LamUV^2  (alpha pure number)
alpha = sp.Symbol('alpha', positive=True)
G_ind = 1/(alpha*N*LamUV**2)
# the corpus' quoted relation G*Lambda^2 = 192 pi^2 / N  (with Lambda the cutoff)
GL2 = sp.simplify(G_ind * LamUV**2)
print(f"   1/G = alpha*N*Lambda_UV^2  =>  G*Lambda_UV^2 = {GL2}")
print(f"   => G*Lambda_UV^2 = 1/(alpha*N) : the cutoff Lambda_UV CANCELS,")
print(f"      leaving a pure number /N (corpus: 192 pi^2 / N with alpha=1/(192 pi^2)).")
alpha_val = 1/(192*sp.pi**2)
GL2_val = GL2.subs(alpha, alpha_val)
print(f"   with alpha = 1/(192 pi^2):  G*Lambda_UV^2 = {sp.simplify(GL2_val)}")
print(f"   This is WEIGHT 0 (pure number/N) => fixes neither G nor Lambda_UV alone.")
matches_192 = sp.simplify(GL2_val - 192*sp.pi**2/N) == 0
print(f"   matches 192 pi^2 / N ? {matches_192}")

# ----------------------------------------------------------------------
# de Sitter consistency at PHYSICAL numbers (dps>=80): is S_dS = pi/(G Lambda0)
# equal to the observed horizon record count ~ 1e122 ?  (a consistency check,
# NOT a determination)
# ----------------------------------------------------------------------
print("\n" + "="*72)
print("de SITTER N_dS CONSISTENCY (dps 80) - a check, not a determination")
print("="*72)
mp.mp.dps = 80
# Planck units: G = l_P^2 (hbar=c=1). Observed Lambda0 ~ 1.1e-52 m^-2.
# l_P = 1.616255e-35 m ; G = l_P^2 = 2.612e-70 m^2.
l_P = mp.mpf('1.616255e-35')
G_phys = l_P**2
Lambda0_phys = mp.mpf('1.1056e-52')      # observed cosmological constant, m^-2
S_dS = mp.pi/(G_phys*Lambda0_phys)
print(f"   G (Planck area)   = {mp.nstr(G_phys,8)} m^2")
print(f"   Lambda0 (observed)= {mp.nstr(Lambda0_phys,8)} m^-2")
print(f"   S_dS = pi/(G*Lambda0) = N_dS = {mp.nstr(S_dS,8)}")
print(f"   log10(N_dS) = {mp.nstr(mp.log(S_dS,10),8)}  (~122: the famous count)")
# The product G*Lambda0 is what is fixed:
print(f"   G*Lambda0 = pi/N_dS = {mp.nstr(G_phys*Lambda0_phys,8)} (the weight-0 datum)")
print(f"   To get G alone you still need ONE absolute length (here: meter/l_P),")
print(f"   which is exactly the missing weight-(-2) unit. CONSISTENT, not DERIVED.")

print("\n" + "="*72)
print("FINAL: transmutation hardens; Sakharov cancels the cutoff; de Sitter")
print("fixes only the product. NO record-intrinsic weight-(-2) Lambda0 found.")
print("="*72)
