#!/usr/bin/env python3
"""
d34a_harris_lemma_exact.py — v10 D34a: the Harris lemma at finite
depth — the first history-law object. Pin: note-d33 §2 (34e68e2) on
the D33-adjudicated conventions (event poset = next-op-on-wire
closure; gauge = incomparable swaps; the transposition lemma swept at
#156). THE OBJECT: the product-of-local-conditionals measure on typed
causal histories,
    mu(H) = prod over events e of q(e | causal-past(e)),
with THE LOCAL LAW (fixed-budget, per the #152 design standard):
each unsealed record y, at each of its local steps, draws
    birth b = 1/4;
    interact total i_tot = 1/4, split EQUALLY over eligible partners
      (unsealed collar neighbors in the birth graph) — REDISTRIBUTION,
      never dilution of the total;
    idle = the remainder (absorbs i_tot when no partner exists).
An interact (y, x): y initiates (consumes y's local step); x receives
passively (consumes NO local step of x). Idle is a recorded local
event ('n', y). R is sealed (never acts, never receives).
Exact rationals for every law-level gate; the persistence trend is
MEASURED (seeded float race). Gates H1-H6; exit 1 on any failure.
"""
from fractions import Fraction as F
from itertools import permutations

PASS = FAIL = 0
def check(label, ok, detail=""):
    global PASS, FAIL
    tag = "[PASS]" if ok else "[FAIL]"
    if ok: PASS += 1
    else: FAIL += 1
    print(f"  {tag} {label}" + (f"  ({detail})" if detail else ""))

def regs_of(op):
    if op[0] == 'n': return {op[1]}
    return {op[1], op[2]}

def event_poset(acts):
    n = len(acts)
    pred = [set() for _ in range(n)]
    last = {}
    for j, op in enumerate(acts):
        for r in regs_of(op):
            if r in last:
                pred[j] |= pred[last[r]] | {last[r]}
        for r in regs_of(op):
            last[r] = j
    return pred

def past_state(acts, pred, j):
    """The state generated by event j's causal past: (adjacency of the
    birth graph restricted to what j can see, y's active-step count) —
    everything q needs, computed from past events ONLY."""
    sub = [acts[i] for i in sorted(pred[j])]
    A = {'R': {'A'}, 'A': {'R', 'B'}, 'B': {'A'}}
    for op in sub:
        if op[0] == 'b':
            A.setdefault(op[1], set()).add(op[2])
            A[op[2]] = {op[1]}
    return A

def q_local(acts, pred, j):
    """The local conditional of event j given its causal past. The
    initiator's eligible set = its unsealed collar neighbors in the
    birth graph generated by j's past."""
    op = acts[j]
    y = op[1]
    A = past_state(acts, pred, j)
    eligible = sorted(x for x in A.get(y, set()) if x != 'R')
    b, itot = F(1, 4), F(1, 4)
    if op[0] == 'b': return b
    if op[0] == 'i':
        if not eligible or op[2] not in eligible: return F(0)
        return itot / len(eligible)
    # idle: the remainder
    return 1 - b - (itot if eligible else F(0))

def mu_along(acts, order):
    """The product of local conditionals evaluated along a given linear
    order — each event's q still conditioned on its OWN causal past."""
    pred = event_poset(acts)
    p = F(1)
    for j in order:
        p *= q_local(acts, pred, j)
    return p

def linear_extensions(acts):
    pred = event_poset(acts)
    n = len(acts)
    out = []
    for perm in permutations(range(n)):
        inv = {e: i for i, e in enumerate(perm)}
        if all(inv[i] < inv[j] for j in range(n) for i in pred[j]):
            out.append(perm)
    return out

print("[d34a the Harris lemma — the product-of-local-conditionals measure]")

# ---- enumerate small histories ---------------------------------------------
def options_for(acts, y):
    """Record y's possible next local actions given the FULL current
    history (used only to ENUMERATE; each event's weight is still its
    causal-past conditional)."""
    pred = event_poset(acts + [('n', y)])
    A = past_state(acts + [('n', y)], pred, len(acts))
    eligible = sorted(x for x in A.get(y, set()) if x != 'R')
    fresh = f"z{sum(1 for op in acts if op[0] == 'b') + 1}"
    return ([('b', y, fresh)] + [('i', y, x) for x in eligible]
            + [('n', y)])

def enumerate_histories(max_events, actors=('A', 'B')):
    """All histories of <= max_events where at each step SOME unsealed
    record takes its next local action (interleavings included — they
    realize different linearizations/histories; gauge-equal ones are
    identified by the measure gates)."""
    out = [[]]
    frontier = [[]]
    while frontier:
        h = frontier.pop()
        if len(h) >= max_events: continue
        present = list(actors) + [op[2] for op in h if op[0] == 'b']
        for y in present:
            for op in options_for(h, y):
                h2 = h + [op]
                out.append(h2); frontier.append(h2)
    return out

HISTS = enumerate_histories(4)

# H1 (round-1 M1: the draft gate was VACUOUS — mu_along never used the
# order except as multiplication sequence, and the LOTTERY passed it
# 2,872/2,872. The REAL gate: RESEQUENCE-AND-RECOMPUTE — rebuild the
# act list in each linear extension's order, recompute the poset and
# every factor from the resequenced list; the lottery rides along as
# the FAILING CONTROL.)
def mu_of(acts):
    pred = event_poset(acts)
    p = F(1)
    for j in range(len(acts)):
        p *= q_local(acts, pred, j)
    return p
def lottery_prob(acts, j):
    """The OLD architecture: the global sequential lottery (w_none = 1,
    w_birth = U, w_collar = |adjacent unsealed ordered pairs|), evaluated
    on the FULL state at step j (everything before j in the given order)."""
    A = {'R': {'A'}, 'A': {'R', 'B'}, 'B': {'A'}}
    for op in acts[:j]:
        if op[0] == 'b':
            A.setdefault(op[1], set()).add(op[2])
            A[op[2]] = {op[1]}
    uns = sorted(r for r in A if r != 'R')
    U = len(uns)
    pairs = [(y, x) for y in uns for x in A[y] if x != 'R']
    w_tot = 1 + U + len(pairs)
    return F(1, w_tot)
def lottery_of(acts):
    p = F(1)
    for j in range(len(acts)):
        p *= lottery_prob(acts, j)
    return p
ok1 = True
nres = 0
lot_fail = 0
for h in HISTS:
    if len(h) < 2: continue
    exts = linear_extensions(h)
    if len(exts) < 2: continue
    base = mu_of(h)
    lot_base = lottery_of(h)
    for e in exts:
        h2 = [h[k] for k in e]
        nres += 1
        ok1 &= (mu_of(h2) == base)
        if lottery_of(h2) != lot_base: lot_fail += 1
check("H1 LINEARIZATION-INDEPENDENCE, THE REAL GATE (round-1 M1): mu "
      "RECOMPUTED from the RESEQUENCED act list equals mu on the original "
      "for every linear extension of every enumerated history; the GLOBAL "
      "LOTTERY runs the same gate as the FAILING CONTROL (the draft's "
      "order-argument gate was vacuous — the lottery passed it — "
      "disclosed)", ok1 and lot_fail > 0,
      f"{nres} resequence-and-recompute cases, mu invariant in all; the "
      f"lottery control fails {lot_fail} of them")

# H2: restriction consistency (per-record local normalization telescopes)
ok2 = True
ncyl = 0
for h in HISTS:
    if len(h) >= 4: continue
    present = ['A', 'B'] + [op[2] for op in h if op[0] == 'b']
    for y in present:
        tot = F(0)
        pred_len = len(h)
        for op in options_for(h, y):
            h2 = h + [op]
            pred2 = event_poset(h2)
            tot += q_local(h2, pred2, pred_len)
        ok2 &= (tot == 1)
        ncyl += 1
# round-1 M2: the draft printed "(restriction)_* mu_{n+1} = mu_n" — FALSE.
# The truth, exhibited: summing mu over ALL one-event extensions gives
# |present(h)| * mu(h) (each record contributes telescope 1), so mu is
# NOT a measure on its own history space (Sigma mu over depth-1 = 2);
# reception PLACEMENTS are unpriced. What IS gated: the per-record
# telescope. The measure-completing clock/placement law is d34b's.
ok2b = True
s1 = F(0)
for h in HISTS:
    if len(h) == 1: s1 += mu_of(h)
for h in HISTS:
    if len(h) >= 3: continue
    present = ['A', 'B'] + [op[2] for op in h if op[0] == 'b']
    tot = F(0)
    for y in present:
        for op in options_for(h, y):
            tot += mu_of(h + [op]) / mu_of(h)   # mu_of([]) == 1
    ok2b &= (tot == len(present))
check("H2 PER-RECORD CONSISTENCY [exact] + THE HONEST RESTATEMENT "
      "(round-1 M2): each record's next-local-action conditional sums to "
      "1 (the telescope — gated); but the FLAT pushforward over all "
      "one-event extensions equals |present|*mu, NOT mu — mu = prod(q) is "
      "the covariant WEIGHT SYSTEM (the decision half of a Harris "
      "factorization), not yet a measure on typed causal histories; the "
      "draft's printed restriction identity is WITHDRAWN; the clock/"
      "placement law that prices receptions is the named d34b object",
      ok2 and ok2b and s1 == 2,
      f"{ncyl} record-sums exactly 1; flat pushforward = |present|*mu at "
      f"every checked history; Sigma mu over depth-1 histories = {s1} "
      f"(not 1)")

# H2b (round-1 M3, OWNED): THE RACE DOES NOT SAMPLE mu AND ITS ACTOR
# DRAW IS NOT GAUGE — the deleted census denominator re-enters as
# 1/|present| in the actor layer (the dilution disease RELOCATED).
def race_path_prob(acts):
    p = F(1)
    for j in range(len(acts)):
        present = ['A', 'B'] + [op[2] for op in acts[:j] if op[0] == 'b']
        pred = event_poset(acts)
        p *= F(1, len(present)) * q_local(acts, pred, j)
    return p
hc = [('b', 'A', 'z1'), ('i', 'A', 'z1'), ('b', 'B', 'z2')]
hd = [('b', 'A', 'z1'), ('b', 'B', 'z2'), ('i', 'A', 'z1')]
rc, rd = race_path_prob(hc), race_path_prob(hd)
ok2c = (rc != rd) and (mu_of(hc) == mu_of(hd))
check("H2b THE RACE-vs-mu CONFRONTATION [exact, owned finding — round-1 "
      "M3]: two linearizations of ONE typed causal history (mu-equal, "
      "gauge-equal per D33) carry DIFFERENT race path probabilities — the "
      "uniform actor draw is NOT gauge, so the race's induced law cannot "
      "equal any function of the causal history (in particular not mu); "
      "diagnosis: the 1/|present| actor factor is the global census "
      "denominator RELOCATED, not removed; the draft's '# gauge choice "
      "only' comment was FALSE (fixed); HF2 stands undischarged; the "
      "exponential-clock (fixed-time) construction is the named route to "
      "an actual measure (d34b)", ok2c,
      f"race({'->'.join(o[0] for o in hc)}) = {rc} vs resequenced {rd} "
      f"(ratio {rd/rc}); mu equal at {mu_of(hc)} both")

# H3: persistence (exact at the law level + a MEASURED race trend)
# law level: every record with an eligible partner carries interact mass
# exactly 1/4 and birth mass exactly 1/4 at EVERY local step, forever —
# the coefficients are step- and size-independent by construction.
ok3a = all(q_local([('b', 'A', 'z1')], event_poset([('b', 'A', 'z1')]), 0)
           == F(1, 4) for _ in [0])
import numpy as np
rng = np.random.default_rng(70260713)
def race(n_events):
    acts = []
    nb = ni = 0
    for _ in range(n_events):
        present = ['A', 'B'] + [op[2] for op in acts if op[0] == 'b']
        y = present[rng.integers(0, len(present))]   # NOT gauge (H2b) —
        # this realization is a SAMPLER OF SOME LAW, not of mu; used here
        # only for the persistence trend, which is law-level anyway
        opts = options_for(acts, y)
        pred = event_poset(acts + [('n', y)])
        ws = []
        for op in opts:
            h2 = acts + [op]
            ws.append(float(q_local(h2, event_poset(h2), len(acts))))
        x = rng.random() * sum(ws)
        c = 0.0
        for op, w in zip(opts, ws):
            c += w
            if x <= c:
                acts.append(op)
                if op[0] == 'b': nb += 1
                if op[0] == 'i': ni += 1
                break
    return nb, ni
nb, ni = race(400)
ok3b = nb > 40 and ni > 40
check("H3 PERSISTENCE: at the law level the birth and interact masses are "
      "1/4 and 1/4 at every local step of every record with a partner — "
      "size-independent BY CONSTRUCTION [exact]; a seeded race realization "
      "shows both densities positive at depth 400 [MEASURED] (success "
      "condition (3); the freeze-out/explosion front HF3 stays open beyond "
      "this depth)", ok3a and ok3b,
      f"race(400): births {nb}, interacts {ni}, idles {400 - nb - ni}")

# H4: no-cap + remote-record locality
h_local = [('b', 'A', 'z1')]
q_before = q_local(h_local + [('i', 'A', 'z1')],
                   event_poset(h_local + [('i', 'A', 'z1')]), 1)
# add a REMOTE cluster on B's side (causally unrelated to A's events)
h_remote = [('b', 'B', 'z9'), ('b', 'z9', 'z8')] + h_local
q_after = q_local(h_remote + [('i', 'A', 'z1')],
                  event_poset(h_remote + [('i', 'A', 'z1')]), 3)
# NOTE: A and B are adjacent at the seed, so B itself is in A's collar;
# the remote CLUSTER (z9, z8) is not. The conditional must be unchanged
# because the added events are incomparable to A's interact... B's birth
# touches B's wire; A's events never touched B's wire here, so the
# cluster is causally unrelated to A's interact: past unchanged.
ok4 = (q_before == q_after) and q_before == F(1, 8)
# round-1 m: the systematic sweep (not one exhibit) — every event of
# every <= 3-event history, under a prepended remote 2-birth cluster on
# an unrelated branch, keeps its factor exactly
REMOTE = [('b', 'B', 'z8'), ('b', 'z8', 'z7')]
nsweep = 0
for h in HISTS:
    if not (1 <= len(h) <= 3): continue
    if any(op[1] in ('B', 'z8', 'z7') or op[2:] and op[2] in ('z8', 'z7')
           for op in h):
        continue          # keep the cluster causally unrelated (A-side only)
    h2 = REMOTE + h
    pred1, pred2 = event_poset(h), event_poset(h2)
    for j in range(len(h)):
        ok4 &= (q_local(h, pred1, j) == q_local(h2, pred2, j + 2))
        nsweep += 1
check("H4 NO-CAP + REMOTE LOCALITY [exact]: the law references no global "
      "size anywhere (coefficients 1/4, 1/4 constant; eligibility from the "
      "initiator's past subgraph only), and adding a causally unrelated "
      "remote cluster leaves the local conditional EXACTLY unchanged "
      "(success conditions (4) and (6))", ok4,
      f"q(interact A->z1 | past) = {q_before} before and after the remote "
      f"cluster; systematic sweep: {nsweep} A-side event factors exactly "
      f"unchanged under the prepended remote cluster (round-1 m)")

# H5: THE LOTTERY CONTRAST GATE — the positive half of the engine claim
# (lottery_prob defined above, shared with H1's failing control)
# (a) linearization DEPENDENCE: pure-birth swaps leave the lottery's
# step weights unchanged (w_tot depends only on counts), so the honest
# exhibit is a type-mixed incomparable pair — an interact on A's side
# vs a birth on B's side (disjoint registers, gauge-swappable per D33):
hc = [('b', 'A', 'z1'), ('i', 'A', 'z1'), ('b', 'B', 'z2')]
# events 1 (interact A,z1) and 2 (birth B) share no register: incomparable
p1 = F(1)
for j in range(3): p1 *= lottery_prob(hc, j)
hd = [('b', 'A', 'z1'), ('b', 'B', 'z2'), ('i', 'A', 'z1')]
p2 = F(1)
for j in range(3): p2 *= lottery_prob(hd, j)
lot_dep = (p1 != p2)
# (b) remote dilution: the same local event's lottery probability drops
# when a remote record exists
q_lot_before = lottery_prob([('b', 'A', 'z1'), ('i', 'A', 'z1')], 1)
q_lot_after = lottery_prob([('b', 'B', 'z9'), ('b', 'A', 'z1'),
                            ('i', 'A', 'z1')], 2)
lot_dil = (q_lot_before != q_lot_after)
check("H5 THE LOTTERY CONTRAST [exact — the positive half of the engine "
      "claim, earned]: the OLD global-lottery architecture on the SAME "
      "typed causal history (a) gives DIFFERENT products along two linear "
      "extensions (an incomparable interact/birth pair — the lottery is "
      "NOT a law on causal histories at all), and (b) DILUTES a local "
      "conditional when a causally unrelated remote record is added; the "
      "local law passes both tests exactly (H1, H4)", lot_dep and lot_dil,
      f"(a) products {p1} vs {p2}; (b) local interact probability "
      f"{q_lot_before} -> {q_lot_after} under a remote birth")

# H6: the conditions scorecard
print("      H6 THE SCORECARD AT ITS HONEST WIDTH [round-1 corrected]: "
      "what exists at receipt grade is THE COVARIANT LOCAL WEIGHT SYSTEM "
      "— the DECISION HALF of a Harris factorization: (1) resequence-"
      "invariant with the lottery as failing control (H1); per-record "
      "consistent (H2); persistent, uncapped, remote-local (H3, H4). What "
      "does NOT yet exist: THE MEASURE — mu is unnormalized on histories "
      "(Sigma = |present|-weighted, H2), reception placements are "
      "unpriced, and the uniform-actor race is NOT gauge (H2b: the census "
      "denominator relocated). The measure-completing object is d34b's "
      "EXPONENTIAL-CLOCK construction (placement priced by local time), "
      "alongside (5) NSE/sealed-preservation and (7) the quantum lift — "
      "all NAMED OPEN. H5 (the lottery conviction) survives unchanged.")
check("H6 the honest scorecard printed (the weight system exists; the "
      "measure is d34b's; conditions (5), (7) open)", True)

print()
total = PASS + FAIL
print(f"ALL CHECKS PASS ({PASS}/{total}: H1-H5 substantive, H6 scorecard)"
      if FAIL == 0 else f"FAILURES: {FAIL}/{total}")
if FAIL: raise SystemExit(1)
