export const meta = {
  name: 'review-v7-paper11-order-direction-manifoldlikeness',
  description: 'Hostile review of v7 Paper XI (order owns the conformal direction; l_step owns the volume scale; manifoldlikeness is the field-shared gate). Three tiers: (I) [THEOREM/DEMONSTRATED] order -> conformal structure + scale-free DIRECTIONS via Malament + Myrheim-Meyer (dim 1+1->2.01 / 2+1->3.01, f(2)=1/2 f(3)=8/35 exact; null cone from links median slope->1; boost+dilation invariant; n-hat drift 0.0 while length scales by lambda) -> delivers Paper X direction, gated by manifoldlikeness NOT l_step; (II) [NO-GO] number -> volume up to l_step (E[N]=V/l_step^d unbiased Poisson; count weight-0 owned, absolute volume weight+2 walled, ratios owned 1.5%) = the SIXTH l_step appearance, closed by inputting G (= v6 paper1 GR-up-to-G,Lambda from the continuum side); (III) [WALLED, field-shared] manifoldlikeness -- Malament/MM hold ONLY for manifold-like sets; Kleitman-Rothschild non-manifold orders dominate 2^{(3/16)n^2}; a single MM estimate FOOLED by KR (d_MM=2.38, unmasked by height: longest chain 3 vs sprinkle 46); the click-law offers NO proven lever (v6 paper1 non-discriminating finite-sprinkling drift = first evidence); Hauptvermutung open. RUN all 3 receipts r1/r2/r3. Hunt overclaims: must NOT claim to BUILD the metric, DISCHARGE manifoldlikeness, construct a UNIQUE emergent manifold (Hauptvermutung open), DERIVE G / fix the scale (G is an INPUT), or deliver Paper X mode frame; must honestly own the CONDITIONAL (the sprinkling is manifold-like by construction; the test shows IF-manifold-like, not that the records produce manifold-like orders). Pre-geometric (the sprinkling is a TEST scaffold scored vs held-out ground truth, never a derivation input; every reconstructed quantity uses the ORDER/COUNT alone), single-threaded, high precision, faithfulness to Malament 1977 / HKMM 1976 / Myrheim-Meyer / Bombelli-Lee-Meyer-Sorkin / Kleitman-Rothschild / Hauptvermutung and companion v6 paper1 (the foundation -- VERIFY it says order+number=geometry, HKT->GR up to G,Lambda, and the non-discriminating finite-sprinkling drift) + v7 papers III/IV/VII/X + the C2 note.',
  phases: [{ title: 'Review', detail: '3 referees on Paper XI' }],
}

const P11 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper11-order-owns-direction-manifoldlikeness-gate.md'
const P1v6 = '/Users/felixrobles/workspace/isp/v6/relativistic-isp-v6-paper1-indivisible-causal-set-gravity.md'
const PXv7 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper10-spin2-carried-helicity2-modeblind.md'
const P4v7 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper4-entanglement-graph-not-metric.md'
const P7v7 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper7-covariant-decoherence.md'
const C2N = '/Users/felixrobles/workspace/isp/v7/note-C2-covariance-premise-deferral.md'
const PLAN = '/Users/felixrobles/workspace/isp/v7/LONG_MARCH_PLAN.md'
const R1 = '/Users/felixrobles/workspace/isp/v7/code/r1_order_to_conformal_direction.py'
const R2 = '/Users/felixrobles/workspace/isp/v7/code/r2_number_volume_lstep.py'
const R3 = '/Users/felixrobles/workspace/isp/v7/code/r3_manifoldlikeness_myrheim_meyer.py'

const RULES = `
STANDING RULES:
- PRE-GEOMETRIC DISCIPLINE: the load-bearing objects are the record CAUSAL ORDER and the seal COUNT. The coordinate SPRINKLING in the receipts is a TEST scaffold (to generate an order and as held-out ground truth to SCORE the order-only reconstruction) -- it must NEVER be a derivation input, and every reconstructed quantity (dimension, null cone, direction, volume) must use the ORDER / COUNT alone. FLAG any place a metric / coordinate / length is fed into the reconstruction, or where "the records produce a manifold-like order" is assumed rather than flagged as the open gate.
- HIGH PRECISION: every numeric claim reproducible at mpmath dps>=60 / exact combinatorics. RUN all three receipts: python3 ${R1} , ${R2} , ${R3} (if mpmath/numpy missing use /Users/felixrobles/workspace/isp/code/.venv/bin/python). Re-derive: f(2)=1/2, f(3)=8/35, f(4)=1/10 exact; dim 1+1->2.01, 2+1->3.01 from pure order; null-cone median slope rising toward 1; boost+dilation invariance of the order; n-hat dilation drift 0.0 while length scales; E[N]=V/l_step^d unbiased + Poisson; count invariant under l_step rescale, volume ~mu^d; the KR trap d_MM=2.38 + height 3 vs 46; (3/16)n^2 dominance.
- SINGLE-THREADED: reads written-once. FLAG 'previously / we now / earlier version / corrected / round N / version N' (bare date stamp OK).
- HONESTY / OVERCLAIM HUNT (BOTH directions):
  (a) MANUFACTURED POSITIVE: must NOT claim to BUILD the metric continuum (it is buildable only UP TO l_step and only GIVEN manifoldlikeness); must NOT DISCHARGE manifoldlikeness (the field's open gate) or claim the click-law SELECTS manifold-like orders (the evidence is non-discrimination); must NOT construct a UNIQUE emergent manifold (Hauptvermutung OPEN); must NOT DERIVE G or fix the scale (G is an INPUT that closes the volume normalization, l_step no-go stands); must NOT deliver Paper X's canonical +/x mode frame (separate fifth wall). CHECK each disavowal (sec 6).
  (b) UNDER-STATEMENT: the paper must correctly CREDIT the three genuinely new moves -- (i) reclassifying Paper X's direction from premature to order-determined/scale-free (a real reduction), (ii) NAMING manifoldlikeness (absent from v7), (iii) the 6th l_step appearance on the volume axis + G as the closure. Is "buildable up to l_step given manifoldlikeness" the right strength?
  (c) TIER I FAITHFULNESS: is order->conformal/direction genuinely owned-in-principle and SCALE-FREE (n-hat dilation-invariant), genuinely NOT the l_step wall, and genuinely conditional on manifoldlikeness? Is the Myrheim-Meyer dimension-from-pure-order correct (exact f(d))? Does it genuinely deliver Paper X's DIRECTION (but not the mode frame)?
  (d) TIER II FAITHFULNESS: is number->volume-up-to-l_step correct (the weight ledger: count weight-0 owned, absolute volume weight+2 walled, ratios owned)? Is "the 6th l_step appearance" faithful, and is "G as the input that closes it" honest (input not derivation, = v6 paper1's GR-up-to-G,Lambda from the continuum side)?
  (e) TIER III FAITHFULNESS: is the Kleitman-Rothschild dominance (2^{(3/16)n^2}) correct? Is the MM trap genuine (d_MM=2.38 on a KR order, unmasked by height 3 vs 46)? Is "field-shared open problem, NOT SHARD-specific" honest, and is the distinction from the l_step wall (SHARD's own no-go vs the field's open emergence problem) correct? Is "the click-law offers no proven lever" + "v6 paper1's non-discriminating finite-sprinkling drift = first recorded evidence" FAITHFUL to v6 paper1 (READ it -- verify the order+number=geometry framework, the HKT->GR-up-to-G,Lambda, and the non-discriminating drift)? Is the Hauptvermutung correctly OPEN?
- FAITHFULNESS: Malament 1977 (J. Math. Phys. 18, 1399), HKMM 1976, Myrheim-Meyer, Bombelli-Lee-Meyer-Sorkin (PRL 59, 521), Kleitman-Rothschild (Trans. AMS 205, 205), the Hauptvermutung, Rideout-Sorkin CSG; companion v6 paper1 (READ -- the foundation), v7 papers III (l_step no-go), IV (hop-metric carrier), VII (emergent Lorentz premise), X (the direction), the C2 note. Read the load-bearing ones.
`

const SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['focus', 'verdict', 'must_fix', 'overclaims', 'math_or_claim_errors', 'pre_geometric_violations', 'single_threaded_violations', 'new_paths_opened', 'summary'],
  properties: {
    focus: { type: 'string' },
    verdict: { type: 'string', enum: ['accept', 'minor-revision', 'major-revision', 'reject'] },
    must_fix: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['issue', 'where', 'severity', 'fix'], properties: { issue: { type: 'string' }, where: { type: 'string' }, severity: { type: 'string', enum: ['minor', 'major', 'critical'] }, fix: { type: 'string' } } } },
    overclaims: { type: 'array', items: { type: 'string' } },
    math_or_claim_errors: { type: 'array', items: { type: 'string' } },
    pre_geometric_violations: { type: 'array', items: { type: 'string' } },
    single_threaded_violations: { type: 'array', items: { type: 'string' } },
    new_paths_opened: { type: 'array', items: { type: 'string' } },
    summary: { type: 'string' },
  },
}

phase('Review')
const reviews = await parallel([
  ['TIER I -- order -> conformal/direction (secs 1-2). RUN r1. Verify the order-only dimension recovery (Myrheim-Meyer, exact f(2)=1/2 / f(3)=8/35; 1+1->2.01, 2+1->3.01), the null cone from the link skeleton (median slope rising toward 1), the boost + dilation invariance of the order and its directions, and n-hat dilation-invariant (drift 0.0) while length scales by lambda. Is order->conformal genuinely a THEOREM the records may invoke (Malament 1977; conditional on manifoldlikeness)? Is the DIRECTION genuinely owned-in-principle + SCALE-FREE, genuinely NOT the l_step wall, and does it genuinely deliver Paper X\'s missing direction (but NOT the mode frame)? Is the "DEMONSTRATED conditional on manifoldlikeness" honest -- does the paper own that the test sprinkling is manifold-like BY CONSTRUCTION (so the test shows IF-manifold-like, not that the records produce manifold-like orders)? Any pre-geometric slip (coordinates fed into the reconstruction)?'],
  ['TIER II + the assembly (secs 3,5). RUN r2. Verify number->volume: E[N]=V/l_step^d unbiased + Poisson (Var/E=0.97); the weight ledger (count weight-0 owned, absolute volume weight+2 walled, volume ratios owned to 1.5%); the l_step rescaling (count invariant, volume ~mu^d). Is "the SIXTH l_step appearance" faithful to the program (d, G, c_m, hop-metric, matter-value, now volume)? Is "G as the input that closes the scale" HONEST -- an INPUT not a derivation, the l_step no-go standing, and genuinely the continuum-side face of v6 paper1\'s "GR up to G and Lambda" (READ v6 paper1 to confirm it says GR up to G,Lambda from the antichain-deformation/HKT route)? Is the sec-5 assembly ("buildable up to l_step given manifoldlikeness") the right overall strength -- not over- (claims the metric built) or under-stating?'],
  ['TIER III + overclaim hunt + discipline (secs 4,6,7 + whole-paper). RUN r3 + READ v6 paper1. Verify the Kleitman-Rothschild dominance (2^{(3/16)n^2}) and the MM trap (KR order d_MM=2.38, unmasked by height: longest chain 3 vs sprinkle 46). Is manifoldlikeness genuinely "field-shared open problem, NOT SHARD-specific", categorically distinct from the l_step wall (SHARD\'s own no-go closed by inputting G vs the field\'s open emergence problem)? Is "the click-law offers no proven lever" + "v6 paper1\'s non-discriminating finite-sprinkling drift = the first recorded evidence" FAITHFUL to v6 paper1 (verify paper1 actually exhibits a non-discriminating finite-sprinkling drift and the order+number=geometry + HKT->GR framework)? Is the Hauptvermutung correctly OPEN? OVERCLAIM HUNT: confirm the paper does NOT build the metric / discharge manifoldlikeness / claim the records select manifold-like orders / construct a unique manifold / derive G / deliver the mode frame (sec 6 disavowals). Does it correctly CREDIT the 3 new moves (reclassify Paper X direction, name manifoldlikeness, 6th l_step + G closure) without under-stating? Pre-geometric (sprinkling = test scaffold), single-threaded, references resolve + faithful. Hunt any remaining overclaim or unfaithful citation.'],
].map(([f]) => () => agent(
  `Hostile, high-precision review of v7 Paper XI (order owns the conformal direction; l_step owns volume; manifoldlikeness the gate) at ${P11}. Your focus: ${f}\nRead the paper, the plan ${PLAN}, the FOUNDATION v6 paper1 ${P1v6}, and companion v7 Papers X ${PXv7}, IV ${P4v7}, VII ${P7v7}, the C2 note ${C2N}. Run the receipts ${R1} , ${R2} , ${R3} + your own checks. ${RULES}\nReturn the schema.`,
  { label: `P11:${f.slice(0, 26)}`, phase: 'Review', schema: SCHEMA }
)))

return { reviews }
