export const meta = {
  name: 'review-v7-paper9-chiral-gap-and-chirality-nogos',
  description: 'Hostile review of v7 Paper IX (closed chiral-gap law + PSG-ingredient functor + two chirality no-gos), which settles Paper VIII sec8s three matter-sector prerequisites. Verify THE THEOREM (sec2): the oriented minimum is the alternating-by-weight orientation eps_a=(-1)^{|a|-1}, the two-value collapse T(s)=-[prod(1-s_i)-1] in {-(2^n-1) on all-minus, +1 on the other 2^n-1 states}, closed form m_hat_min(n)=-ln(1-2^-n)-delta_n: strictly positive at finite n, asymptotically gapless as n->inf, prefactor EXACTLY 1; verified to corpus anchors at dps130 (n=5 0.031748698 was EXACT not a UB) + EXHAUSTIVE brute force at n=2,3; honestly graded as theorem-mod-a-finite-global-optimality-lemma (brute-forced to n=4), NOT an unconditional all-n theorem. Verify NO-GO 1 (sec3-4): K-hat x Aut(K) builds (168=GL(3,2) at n=3, 1+7+7+1 multiplet) but is the SPLIT extension => the PSG-INGREDIENT group NOT Wens PSG (whose H^2(SG,IGG) content needs a SPACE GROUP = emergent geometry, l_step-walled); must NOT claim the record PSG is derived. Verify NO-GO 2 (sec5): the ledger layer is handedness-BLIND (gap = pure function of orientation sigma; Weyl handedness m on a different SO(3)-fiber layer), parity is JOINT (sigma,m)->(sigma-bar,-m) with parity-invariant gap, so a bridge sigma|->m would be parity-ODD on parity-SYMMETRIC data = undetermined => supplied by the coupling g; the chirality bridge is NOT record-forced (a proved no-go, upgrading paper8 open-item-2). RUN all 3 receipts p9a/p9b/p9c. Hunt overclaims BOTH directions: must NOT predict any mass/ratio, NOT claim Wens PSG derived, NOT claim an unconditional all-n gap theorem, NOT claim the bridge is merely open (it is now a proved no-go); must correctly credit the closed theorem + the two no-gos as PROGRESS (sharper boundary). Pre-geometric (no emergent geometry/space group/fiber handedness as INPUT - their absence IS the no-go content), single-threaded, high precision, faithfulness to Wen PSG cond-mat/0107071 (H^2(SG,IGG), SG=space group) / Levin-Wen / Nielsen-Ninomiya / Ginsparg-Wilson / Griffiths-Toulouse and companion v6 papers 7/8/9/14 + v7 papers III/VIII.',
  phases: [{ title: 'Review', detail: '3 referees on Paper IX' }],
}

const P9 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper9-chiral-gap-and-chirality-nogos.md'
const P8v7 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper8-matter-sector-mode-wall.md'
const P3v7 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper3-seal-spacing-no-go.md'
const P8v6 = '/Users/felixrobles/workspace/isp/v6/relativistic-isp-v6-paper8.md'
const P9v6 = '/Users/felixrobles/workspace/isp/v6/relativistic-isp-v6-paper9.md'
const PLAN = '/Users/felixrobles/workspace/isp/v7/LONG_MARCH_PLAN.md'
const RA = '/Users/felixrobles/workspace/isp/v7/code/p9a_chiral_gap_closed.py'
const RB = '/Users/felixrobles/workspace/isp/v7/code/p9b_psg_ingredient_functor.py'
const RC = '/Users/felixrobles/workspace/isp/v7/code/p9c_chirality_bridge_nogo.py'

const RULES = `
STANDING RULES to enforce:
- PRE-GEOMETRIC DISCIPLINE: every derivation quantity must be a record-internal code / character / finite group / KL gap (nats). The things proved ABSENT -- a space group / emergent geometry (no-go 1), a ledger->fiber handedness map (no-go 2) -- must appear ONLY as what the records cannot supply, NEVER as a derivation input. FLAG any emergent geometry, lattice translation, spatial momentum, or fiber handedness smuggled in as a premise.
- HIGH PRECISION: every numeric claim reproducible at mpmath dps>=90 (closed gap law dps130) / finite-group-exact / exhaustive. RUN all three receipts: python3 ${RA} , ${RB} , ${RC} (if mpmath/numpy missing use /Users/felixrobles/workspace/isp/code/.venv/bin/python), plus your own checks. Re-derive: the two-value identity T(s) in {-(2^n-1),+1}; the closed form m_hat_min(n)=-ln(1-2^-n)-delta_n vs the corpus anchors (n=3 0.133530982072, n=4 0.064538521138, n=5 0.031748698315) -- CONFIRM the n=5 'sampled UB' was the EXACT minimum; prefactor m*2^n->1; the EXHAUSTIVE brute force at n=2 (8 orientations) and n=3 (128); |Aut(K)|=168=|GL(3,2)|=(7)(6)(4); the split-extension fact; the gap as a pure function of sigma + its parity-invariance m_hat(sigma)=m_hat(sigma-bar).
- SINGLE-THREADED: reads written-once. FLAG 'previously / we now / earlier version / corrected / round N / campaign / version N' (a bare date stamp is allowed). Also flag any content-level re-import of a source-SUPERSEDED number (e.g. the retired 0.27*2^-n fit -- the paper should carry the CURRENT exact closed form).
- HONESTY / OVERCLAIM HUNT (BOTH directions):
  (a) MANUFACTURED POSITIVE: the paper must NOT predict any particle mass/ratio (a mass ratio stays GATED); must NOT claim the record group K-hat x Aut(K) IS Wen's PSG (it is the INGREDIENT group; the cohomological content is walled); must NOT claim an UNCONDITIONAL all-n gap theorem (it is theorem-mod-a-finite-global-optimality-lemma, exhaustive only through n=4); must NOT claim to close the interacting GW flow. CHECK each is disavowed (sec 6-7).
  (b) UNDER-STATEMENT: the paper must correctly CREDIT the result as PROGRESS -- one conjecture CLOSED into a theorem, two prerequisites turned from open gaps into PROVED no-gos, the matter sector ending MORE resolved. Is 'theorem + two no-gos' the right framing, and is the second no-go correctly upgraded from 'open gap' (paper8 open-item-2 / Paper VIII non-claim) to a PROVED impossibility -- or is the proof actually weaker (a restatement) than claimed?
  (c) THE THEOREM FAITHFULNESS: is the alternating-by-weight orientation genuinely the GLOBAL minimizer (is the brute force truly exhaustive at n=2,3; is the n=4 random-challenge adequate; is 'mod a finite global-optimality lemma' the honest grade vs an overclaimed all-n theorem)? Is the two-value collapse T(s) identity correct? Is the closed form's strict-positivity-at-finite-n / asymptotic-gaplessness / prefactor-1 all correct and correctly concluded (asymptotically gapless, NOT finite-n gapless)?
  (d) NO-GO 1 FAITHFULNESS: is 'no Wen-PSG without geometry' faithful to Wen (cond-mat/0107071): is the PSG content genuinely H^2(SG,IGG) with SG the SPACE GROUP, and is Aut(K) genuinely a permutation group with no space-group structure, making the record extension SPLIT? Is the boundary between 'PSG-ingredient group built' (claimed) and 'Wen-PSG derived' (disavowed) crisp and correct?
  (e) NO-GO 2 FAITHFULNESS: is the handedness-blindness genuine (the gap really a pure function of sigma with no m), is parity genuinely a JOINT symmetry with a parity-invariant gap, and does 'parity-odd map on parity-symmetric data => undetermined => supplied by g' genuinely PROVE the bridge is not record-forced (vs merely restate the different-layer gap)? Is the achiral<->m=0 consistency + the g-dependence of the asymmetry faithful to Paper 9?
- FAITHFULNESS to sources: Wen PSG cond-mat/0107071 (the H^2(SG,IGG) extension, SG=space group), Wen 1305.1045, Levin-Wen cond-mat/0404617, Nielsen-Ninomiya, Ginsparg-Wilson, Griffiths-Toulouse; companion v6 paper 7 (W), 8 (K-hat Thm 5.1, GL(3,2) 1+7+7+1, the oriented branch + O2), 9 (Weyl seed, SO(3) fiber, coupling g), 14 (GW/index/anomaly, O8); v7 papers III (l_step wall), VIII (the matter sector + sec8 prerequisites). Read them.
`

const SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['focus', 'verdict', 'must_fix', 'overclaims', 'math_or_claim_errors', 'pre_geometric_violations', 'single_threaded_violations', 'new_paths_opened', 'summary'],
  properties: {
    focus: { type: 'string' },
    verdict: { type: 'string', enum: ['accept', 'minor-revision', 'major-revision', 'reject'] },
    must_fix: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['issue', 'where', 'severity', 'fix'], properties: { issue: { type: 'string' }, where: { type: 'string' }, severity: { type: 'string', enum: ['minor', 'major', 'critical'] }, fix: { type: 'string' } } } },
    overclaims: { type: 'array', items: { type: 'string' } },
    math_or_claim_errors: { type: 'array', items: { type: 'string' } },
    pre_geometric_violations: { type: 'array', items: { type: 'string' } },
    single_threaded_violations: { type: 'array', items: { type: 'string' } },
    new_paths_opened: { type: 'array', items: { type: 'string' } },
    summary: { type: 'string' },
  },
}

phase('Review')
const reviews = await parallel([
  ['THE CLOSED GAP THEOREM (sec 2). RUN p9a. Re-derive the two-value collapse identity T(s)=-[prod_i(1-s_i)-1] in {-(2^n-1) on all-minus, +1 on the other 2^n-1 states} (verify exactly for several n); the scalar fixed point and the closed form m_hat_min(n)=-ln(1-2^-n)-delta_n; the corpus anchors at dps130 (n=3 0.133530982072, n=4 0.064538521138, n=5 0.031748698315 -- CONFIRM the n=5 sampled-UB was EXACT); strictly-positive-at-finite-n, asymptotically-gapless-as-n->inf, prefactor m*2^n->1 EXACTLY. CRITICAL: is the alternating-by-weight orientation genuinely the GLOBAL minimizer? Re-run / independently check the EXHAUSTIVE brute force at n=2 (8) and n=3 (128); judge whether the n=4 random challenge is adequate and whether "theorem mod a finite global-optimality lemma (brute-forced to n=4)" is the HONEST grade or an overclaimed all-n theorem. Is "Paper VIII conjecture -> theorem" correctly scoped?'],
  ['THE PSG FUNCTOR + NO-GO 1 (secs 3-4). RUN p9b + read v6 paper8 + Wen cond-mat/0107071. Verify |Aut(K)|=168=|GL(3,2)|=(7)(6)(4) at n=3 and the 1+7+7+1 multiplet; the well-defined action; the SPLIT-extension fact (Z2-valued orientation + honest permutations => no forced cocycle). Is "no Wen-PSG without geometry" FAITHFUL to Wen: is the PSG content genuinely H^2(SG,IGG) with SG = the SPACE GROUP (lattice translations + point group), and is Aut(K) genuinely a finite permutation group with NO space-group structure (no translations/momentum/projective phases)? Is the boundary between "PSG-INGREDIENT group built" (claimed, SYNTHESIS) and "Wen-PSG derived" (disavowed, NO-GO) crisp and correct -- not overclaiming the record group is Wen\'s PSG, not understating what genuinely builds? Pre-geometric: is any space-group/emergent-geometry structure smuggled in?'],
  ['NO-GO 2 + OVERCLAIM HUNT both directions + discipline (secs 1,5,6,7,8). RUN p9c + read v6 paper9. (5) Is the handedness-blindness genuine (the gap m_hat a pure function of sigma, no m), parity genuinely a JOINT symmetry with parity-invariant gap m_hat(sigma)=m_hat(sigma-bar), and does "a bridge would be parity-odd on parity-symmetric data => undetermined => supplied by coupling g" genuinely PROVE the bridge is not record-forced, or merely RESTATE the different-layer gap (is the upgrade from "open gap" to "proved no-go" real)? Achiral<->m=0 + g-dependence faithful to Paper 9? (a) Does the paper AVOID predicting any mass/ratio, AVOID claiming Wen-PSG derived, AVOID an unconditional all-n theorem, AVOID claiming the bridge merely open? (b) Does it correctly CREDIT the progress (1 conjecture closed + 2 proved no-gos = sharper boundary, matter sector MORE resolved) without under-stating? (sec 6) Is the "what remains gated" (Wen-PSG/geometry + mode-selecting Hamiltonian/fifth wall + interacting flow) honest and complete? Pre-geometric, single-threaded (incl. NO re-import of the retired 0.27 fit), references resolve + faithful (Wen PSG, Griffiths-Toulouse, v6 7/8/9/14, v7 III/VIII).'],
].map(([f]) => () => agent(
  `Hostile, high-precision review of v7 Paper IX (closed chiral-gap law + PSG-ingredient functor + two chirality no-gos) at ${P9}. Your focus: ${f}\nRead the paper, the plan ${PLAN}, companion v7 Papers III ${P3v7}, VIII ${P8v7}, and the v6 sources paper8 ${P8v6}, paper9 ${P9v6}. Run the receipts ${RA} , ${RB} , ${RC} + your own sympy/mpmath/numpy checks. ${RULES}\nReturn the schema.`,
  { label: `P9:${f.slice(0, 26)}`, phase: 'Review', schema: SCHEMA }
)))

return { reviews }
