export const meta = {
  name: 'review-v7-paper7-covariant-decoherence',
  description: 'Hostile review of v7 Paper VII (the decoherence layer is covariant on one emergence premise; colored noise structural; interacting-field statevector = the shared wall). Verify: the SUPPLIED ingredients (seal = self-adjoint weight-0 Lorentz scalar E=E^2=E*; Tier-B kernel f(s^2) LI + positive-type, Gram min-eig +2.78e-9); the CONDITIONAL inheritance (locality is the load-bearing gap; point-local scalar seal commutes with spacelike probe to all orders, region-smeared FAILS at n=1; so the decoherence layer inherits GDC-2025 all-orders microcausality + spacelike TS-integrability IFF the diamond coarse-grains to a point-local scalar seal density, collar->0 -- ONE sharp borrowable premise, NOT a theorem); the STRUCTURAL claim (colored != white is forced by the discreteness UV cutoff, avoiding the infinite-heating catastrophe BY CONSTRUCTION -- but the kernel is NOT derived: weight-0 content wrong-type, quartic template one-of-many); the WALL (objective interacting-field statevector = Fedida-2025 unitary inequivalence = the whole field shares it, SHARD no worse off; stay stochastic-linear vs the deterministic-nonlinear no-go). RUN both receipts c1/c2. Hunt overclaims BOTH directions (must NOT claim a full covariance solution, a derived kernel, an objective interacting-field statevector, or the point-local premise as a theorem; must correctly credit the supplied ingredients + conditional inheritance + structural coloring). Pre-geometric (Lorentz/metric only EMERGENT, never a derivation input), single-threaded, high precision, faithfulness to GDC 2507.06954 / Fedida 2506.14693 / Tumulka / GRW-CSL / Diosi-Penrose / Barandes and companion Papers I/III.',
  phases: [{ title: 'Review', detail: '3 referees on Paper VII' }],
}

const P7 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper7-covariant-decoherence.md'
const P1 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper1-record-click-law.md'
const P3 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper3-seal-spacing-no-go.md'
const PLAN = '/Users/felixrobles/workspace/isp/v7/LONG_MARCH_PLAN.md'
const C1 = '/Users/felixrobles/workspace/isp/v7/code/c1_lorentz_scalar_seal_mcc.py'
const C2 = '/Users/felixrobles/workspace/isp/v7/code/c2_derived_noise_kernel.py'

const RULES = `
STANDING RULES to enforce:
- PRE-GEOMETRIC DISCIPLINE: the seal, content, and kernel are record-internal objects (a projection, a KL number, a function of the substrate interval invariant). NO metric / Lorentz group used as a derivation INPUT -- the Lorentz group enters ONLY as the EMERGENT structure the records are tested against. FLAG any spacetime / metric / Lorentz frame smuggled in as a premise. The microcausality must be stated against the FRAME-INVARIANT record causal order, not an assumed spacetime.
- HIGH PRECISION: every numeric claim reproducible at mpmath dps>=100 / lattice model. RUN both receipts: python3 ${C1} , ${C2} (if mpmath missing use /Users/felixrobles/workspace/isp/code/.venv/bin/python), plus your own checks. Re-derive: seal E=E*=E^2 (scalar/self-adjoint); kernel Gram min-eig +2.78e-9 (positive-type/LI); the point-local scalar seal commutator VANISHES vs a spacelike probe to all orders tested while the REGION-SMEARED seal FAILS at first order (the load-bearing conditional); the white-noise heating integral DIVERGES (infinite heating) while quartic converges; the kernel NOT uniquely derived (two independent failure counts: weight-0 content wrong-type for G(s^2); quartic template one positive-type profile among many).
- SINGLE-THREADED: reads written-once. FLAG 'previously / we now / earlier version / corrected / round N / campaign / version N' (a bare date stamp is allowed).
- HONESTY / OVERCLAIM HUNT (BOTH directions):
  (a) MANUFACTURED POSITIVE: the paper must NOT claim a full covariant collapse theory, an objective relativistic interacting-field statevector, or a DERIVED noise kernel (it is one positive-type profile among many; the weight-0 content is the wrong TYPE for a two-point function). Must NOT claim the point-local emergence premise is a THEOREM (it is a motivated, named, UNPROVED hypothesis; the inheritance is CONDITIONAL on it). CHECK each is disavowed in sec 7.
  (b) UNDER-STATEMENT: the paper must correctly CREDIT what SHARD supplies -- the two non-trivial GDC ingredients (scalar seal + LI positive-type kernel) outright, the conditional all-orders microcausality inheritance, and the STRUCTURAL coloring (avoiding the infinite-heating catastrophe by construction). Is "conditional positive" the right strength? Is the noise result "coloring is structural" (NOT "kernel derived") stated at exactly the right grade?
  (c) THE CONDITIONAL FAITHFULNESS: is LOCALITY genuinely the ONLY load-bearing gap (are the scalar-seal and LI-kernel ingredients genuinely discharged, or is "scalar under the EMERGENT Lorentz action" a hidden second gap folded into the premise -- and is that folding honest)? Is the point-local <=> microcausality inheritance faithful to GDC 2025's all-orders recursion, and is the finite-causal-lattice model a legitimate operationalization (region-smeared FAILS at n=1)? Is "ONE sharp borrowable premise" a genuine reduction of the open surface, or a relabeling?
  (d) THE WALL: is the objective interacting-field statevector genuinely the FIELD'S SHARED wall (Fedida 2025 unitary inequivalence -- interacting QFT lacks unitarily-equivalent Hilbert spaces across Cauchy surfaces), blocking Tumulka/CSL/GRW EQUALLY so SHARD is no worse off? Is the residue factorization B=B1(field TS-unitary)xB2(insert collapse) honest, with every factor except B1 discharged? Is "stay stochastic-linear to avoid the deterministic-nonlinear signalling no-go" correctly invoked? Is the flash/event ontology scoping (free-field covariant constructions exist; objective interacting-field wavefunctional does not) faithful?
- FAITHFULNESS to sources: GDC 2025 (arXiv:2507.06954, the microcausality/finite-energy theorem), Fedida 2025 (arXiv:2506.14693, unitary inequivalence), Tumulka 2006 (rGRWf), GRW/CSL, Diosi-Penrose (gravitational decoherence, the v5 p2 target), Barandes; companion Paper I (seal=projection, kernel emergent Tier-B, microcausality NOT yet claimed), Paper III (weight-0 classification). Read them. NOTE the Hsu deterministic-nonlinear no-go and the 2026 Diosi follow-up are cited descriptively from the plan -- check the paper does not lean load-bearingly on an unverifiable arXiv id (the load-bearing anchors are GDC + Fedida).
`

const SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['focus', 'verdict', 'must_fix', 'overclaims', 'math_or_claim_errors', 'pre_geometric_violations', 'single_threaded_violations', 'new_paths_opened', 'summary'],
  properties: {
    focus: { type: 'string' },
    verdict: { type: 'string', enum: ['accept', 'minor-revision', 'major-revision', 'reject'] },
    must_fix: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['issue', 'where', 'severity', 'fix'], properties: { issue: { type: 'string' }, where: { type: 'string' }, severity: { type: 'string', enum: ['minor', 'major', 'critical'] }, fix: { type: 'string' } } } },
    overclaims: { type: 'array', items: { type: 'string' } },
    math_or_claim_errors: { type: 'array', items: { type: 'string' } },
    pre_geometric_violations: { type: 'array', items: { type: 'string' } },
    single_threaded_violations: { type: 'array', items: { type: 'string' } },
    new_paths_opened: { type: 'array', items: { type: 'string' } },
    summary: { type: 'string' },
  },
}

phase('Review')
const reviews = await parallel([
  ['THE INHERITANCE SPINE (secs 2-4) -- the conditional positive. RUN c1. Are the two GDC ingredients genuinely SUPPLIED: (sec2) the seal a self-adjoint weight-0 scalar (E=E*=E^2), (sec3) the kernel LI + positive-type (Gram min-eig +2.78e-9)? Is LOCALITY genuinely the ONLY remaining load-bearing gap, or is "scalar under the EMERGENT Lorentz action" a hidden SECOND gap -- and if folded into the premise, is that honest? Re-derive the finite-causal-lattice MCC: does the POINT-LOCAL scalar seal commutator vanish vs a spacelike probe to all orders tested, and does the REGION-SMEARED seal FAIL at first order? Is the inheritance (point-local <=> GDC all-orders microcausality + spacelike TS-integrability) faithful to GDC 2025? Is the "collar->0 point-local scalar seal density" premise correctly tagged CONDITIONAL (motivated, NOT a theorem), and is "ONE sharp borrowable premise" a genuine reduction of the open surface vs a relabeling?'],
  ['THE STRUCTURAL-NOT-DERIVED + THE WALL (secs 5-6). RUN c2. (5) Is "colored noise is structural-by-construction, NOT a derived kernel" stated at exactly the right grade -- does the kernel genuinely FAIL to be uniquely derived on two independent counts (weight-0 odometer content is the WRONG TYPE for a two-point G(s^2); the quartic positive-type template is one profile among many), AND is the COLORING genuinely forced (the discreteness UV cutoff makes white noise -- which DIVERGES the heating integral, infinite heating -- impossible by construction)? Is the boundary between "coloring structural" (claimed) and "kernel derived" (disavowed) crisp? (6) Is the objective interacting-field statevector genuinely the FIELD-SHARED wall (Fedida 2025 unitary inequivalence), blocking Tumulka/CSL/GRW equally => SHARD no worse off? Is the residue factorization B=B1xB2 honest (every factor except B1(field TS-unitary) discharged)? Is "stochastic-linear vs the deterministic-nonlinear no-go" correctly invoked, and the flash/event-ontology scoping faithful?'],
  ['OVERCLAIM HUNT BOTH directions + discipline + faithfulness (secs 1,7,8). (a) Does the paper AVOID claiming: a full covariance solution, a DERIVED kernel, an objective interacting-field statevector, the point-local premise as a THEOREM? Confirm each disavowal in sec 7. (b) Does it correctly CREDIT the supplied ingredients + the conditional inheritance + the structural coloring without under-stating? Is "conditional positive" the right overall strength? (c) Pre-geometric discipline: is any spacetime / metric / Lorentz frame smuggled in as a derivation INPUT (Lorentz must be EMERGENT-only; microcausality stated against the frame-invariant record causal order)? (d) Single-threaded? Do the references resolve, and is the citation of GDC 2507.06954, Fedida 2506.14693, Tumulka, GRW/CSL, Diosi-Penrose, Barandes, and Papers I/III faithful? Does the paper lean load-bearingly on any unverifiable future-dated arXiv id (the load-bearing anchors must be GDC + Fedida; the Hsu/Diosi follow-ups are descriptive only)? Hunt any remaining overclaim or unfaithful citation.'],
].map(([f]) => () => agent(
  `Hostile, high-precision review of v7 Paper VII (the decoherence layer is covariant on one emergence premise) at ${P7}. Your focus: ${f}\nRead the paper, the plan ${PLAN}, and companion Papers I ${P1}, III ${P3}. Run the receipts ${C1} , ${C2} + your own checks. ${RULES}\nReturn the schema.`,
  { label: `P7:${f.slice(0, 24)}`, phase: 'Review', schema: SCHEMA }
)))

return { reviews }
