export const meta = {
  name: 'review-v7-paper8-matter-sector-mode-wall',
  description: 'Hostile review of v7 Paper VIII (chiral fermions from record structure + the mode-canonicalization wall): a two-part synthesis-plus-fifth-no-go. Verify PART A: the three constructive pieces SHARD owns (exact record Ginsparg-Wilson op evading Nielsen-Ninomiya, GW residual 4e-15, 1 vs 4 Brillouin zeros; lattice index theorem index(D)=Q in 14/14 sectors; anomaly filter Thm 6.1 minimal {1,4,4|2,2,5}) genuinely owned + genuinely the field-missing pieces ("ahead on chiral fermions" defensible not overclaimed); and the mass mechanism "mass = the record gap when protection breaks" = THEOREM on the unoriented branch (gap=W=eta*theta-log cosh eta=0.156109200157240, the three roles spectral-gap/lightest-mass/event-price equal to <1e-40) + only a CONJECTURE on the oriented branch (collapse ~2^-n, exact n=3 0.1335 / n=4 0.0645, asymptotics open, NOT a finished biconditional). Verify PART B: mode-canonicalization is a FIFTH l_step-type wall -- modes gauge-INEQUIVALENT (invariant ledger ranks 1/3/7 => distinct superselection sectors); all 3 routes fail (completeness pushes DOWN the dilution ladder 0.609->0.495->0.368 AWAY from eta_B; xi=1/eta is an algebraic tautology + mode-covariant; variational opposite + firing clock mode-blind E[I]=1; skewed base p=0.2 overshoots W_*); sole external escape RELOCATES the choice. Verify the hierarchy is FORM-ONLY (1/N mode-count, count not corpus-forced ~37 orders short, one calibration survives = Paper V c_m=gamma_G*nu_m^2); and NO mass ratio computable now (doubly gated). RUN both receipts m1/m2. Hunt overclaims BOTH directions: must NOT predict any mass/ratio, NOT claim a finished massless-iff biconditional, NOT claim the PSG group H1(SG,IGG) derived or the ledger-chirality<->Weyl-chirality bridge built, NOT fix the count N; must correctly credit the synthesis + the theorem-grade gap + the fifth wall. Pre-geometric (no continuum field/spinor bundle/mass scale as INPUT), single-threaded, high precision, faithfulness to Levin-Wen / Wen-PSG / Nielsen-Ninomiya / Ginsparg-Wilson / Wen-1305.1045 / Sakharov-Dvali and companion v6 papers 7/8/9/14/10 + Papers II/III/V.',
  phases: [{ title: 'Review', detail: '3 referees on Paper VIII' }],
}

const P8 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper8-matter-sector-mode-wall.md'
const P3 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper3-seal-spacing-no-go.md'
const P5 = '/Users/felixrobles/workspace/isp/v7/relativistic-isp-v7-paper5-cm-free-calibration.md'
const PLAN = '/Users/felixrobles/workspace/isp/v7/LONG_MARCH_PLAN.md'
const P7v6 = '/Users/felixrobles/workspace/isp/v6/relativistic-isp-v6-paper7.md'
const P8v6 = '/Users/felixrobles/workspace/isp/v6/relativistic-isp-v6-paper8.md'
const P14v6 = '/Users/felixrobles/workspace/isp/v6/relativistic-isp-v6-paper14.md'
const M1 = '/Users/felixrobles/workspace/isp/v7/code/v7_m1_psg_gap_chiral_receipt.py'
const M2 = '/Users/felixrobles/workspace/isp/v7/code/m2_mode_canonicalization.py'

const RULES = `
STANDING RULES to enforce:
- PRE-GEOMETRIC DISCIPLINE: every quantity must be a record-internal evidence content / character-ledger rank / lattice index. NO continuum field, spinor bundle, Dirac sea, or mass scale used as a derivation INPUT -- the matter sector's STRUCTURE is read off the records, the unbuilt part is named. FLAG any continuum QFT object presupposed as input rather than derived/named-absent.
- HIGH PRECISION: every numeric claim reproducible at mpmath dps>=90 (mode-canon dps=100) / sympy-exact. RUN both receipts: python3 ${M1} , ${M2} (if mpmath missing use /Users/felixrobles/workspace/isp/code/.venv/bin/python), plus your own checks. Re-derive: eta (e^-eta=tanh eta), the commitment cubic theta^3+theta^2+theta-1=0, W=eta*theta-log cosh eta=0.1561092001572401, the three roles (spectral gap = lightest mass = event price) equal to <1e-40; the oriented collapse exact at n=3 (0.133530982072) and n=4 (0.064539), ratios ~2; the GW residual 4e-15 / index 14/14 / anomaly stack {1,4,4|2,2,5} (from v6 paper14); and for m2: the dilution ladder 0.609>0.495>0.368, the xi=1/eta symbolic tautology (residual 0), xi(h_*)=1.2814 != xi(eta_B)=1.6410 (mode-covariant), the recorded-distinct D=0.00479>0, the invariant ranks [1,3,7], the skewed-base overshoot 0.526>W_*=0.365, E[I]=1 mode-blind.
- SINGLE-THREADED: reads written-once. FLAG 'previously / we now / earlier version / corrected / round N / campaign / version N' (a bare date stamp is allowed).
- HONESTY / OVERCLAIM HUNT (BOTH directions):
  (a) MANUFACTURED POSITIVE: the paper must NOT predict any particle mass or mass RATIO; must NOT claim a finished "massless iff protection-exact" biconditional (only the proven gapped direction + the conjectural gapless one); must NOT claim the PSG group H1(SG,IGG) is DERIVED from record data (the map is to PSG-PROTECTION phenomenologically, via orientation + anomaly filter, NOT the group); must NOT claim the ledger-chirality<->Weyl/PSG-chirality bridge is built; must NOT fix the hierarchy count N. CHECK each is disavowed in secs 6-8.
  (b) UNDER-STATEMENT: the paper must correctly CREDIT what is real -- the three owned constructive pieces (and "ahead on chiral fermions"), the THEOREM-grade unoriented gap W ("one constant three roles"), the fifth-wall NO-GO as a clean result, the form-only hierarchy mechanism. Is "synthesis-plus-no-go" the right framing? Is the gapped half correctly THEOREM and the gapless half correctly CONJECTURE (not blurred)?
  (c) THE SYNTHESIS FAITHFULNESS (Part A): are the three pieces GENUINELY owned by SHARD (verify against v6 paper14: GW identity, index theorem, anomaly filter) and GENUINELY the pieces the Levin-Wen/Wen-PSG program assumes-but-never-builds? Is "ahead on chiral fermions" defensible (Wen's mirror-gapping is anomaly-free-gated + unproven; SHARD's exact record GW + index + anomaly filter is the constructive version) or an overclaim? Is the unoriented/oriented = vector-like/chiral = unprotected/protected = gapped-at-W / gapless dictionary faithful to v6 papers 7-8?
  (d) THE FIFTH WALL (Part B): is the gauge-inequivalence diagnosis genuinely decisive -- are the ledger ranks 1/3/7 genuinely invariant (no record-internal gauge map changes them) => genuinely distinct superselection sectors? Do all THREE routes genuinely fail (completeness HORN A pushes down the ladder away from eta_B + HORN B modes recorded-distinct; route 2 xi=1/eta tautology + mode-covariant + weight-0-internal; route 3 max-content vs completeness OPPOSITE + mode-blind clock + circular gate)? Is "same shape as the l_step / scale no-go" (Paper III) faithful? Is "the sole escape (a matter Hamiltonian selecting a rank) RELOCATES the choice, does not close the wall" honest?
  (e) THE GATED CONCLUSION: is "no single physical mass ratio computable now, doubly gated (the mode wall + the unbuilt chirality bridge + conjectural O2 asymptotics)" honest and load-bearing, and does the paper REFUSE to manufacture the bridge? Is the FORM-ONLY hierarchy (1/N, count not forced, one calibration = Paper V) correctly NOT a value prediction?
- FAITHFULNESS to sources: Levin-Wen cond-mat/0404617, Wen-PSG cond-mat/0107071, Nielsen-Ninomiya Nucl.Phys.B185, Ginsparg-Wilson PRD25, Wen 1305.1045 (anomaly-free-gated mirror gapping), Sakharov/Dvali (1/N hierarchy); companion v6 papers 7 (Thm 9.4, the gap W + one-constant-three-roles), 8 (oriented-gapless scope correction + asymptotics conjecture), 9 (Nielsen-Ninomiya resolution + record Weyl seed), 14 (record GW + index + anomaly filter), 10 (completeness/silent-refinement template); Papers II (mode-dependent firing law + W_*), III (scale no-go + fifth-wall shape), V (c_m=gamma_G*nu_m^2 calibration). Read v6 papers 7/8/14 (paths given) + Papers III/V.
`

const SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['focus', 'verdict', 'must_fix', 'overclaims', 'math_or_claim_errors', 'pre_geometric_violations', 'single_threaded_violations', 'new_paths_opened', 'summary'],
  properties: {
    focus: { type: 'string' },
    verdict: { type: 'string', enum: ['accept', 'minor-revision', 'major-revision', 'reject'] },
    must_fix: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['issue', 'where', 'severity', 'fix'], properties: { issue: { type: 'string' }, where: { type: 'string' }, severity: { type: 'string', enum: ['minor', 'major', 'critical'] }, fix: { type: 'string' } } } },
    overclaims: { type: 'array', items: { type: 'string' } },
    math_or_claim_errors: { type: 'array', items: { type: 'string' } },
    pre_geometric_violations: { type: 'array', items: { type: 'string' } },
    single_threaded_violations: { type: 'array', items: { type: 'string' } },
    new_paths_opened: { type: 'array', items: { type: 'string' } },
    summary: { type: 'string' },
  },
}

phase('Review')
const reviews = await parallel([
  ['PART A: THE SYNTHESIS + THE MASS THEOREM (secs 2-3). RUN m1 + read v6 paper14. Are the three constructive pieces GENUINELY owned (GW identity residual 4e-15, single species 1 vs 4 Brillouin zeros; index(D)=Q in 14/14 flux sectors incl. rough sectors; anomaly filter minimal stack {1,4,4|2,2,5}) and GENUINELY the pieces the Levin-Wen/Wen-PSG program assumes but never builds? Is "ahead on chiral fermions" defensible (Wen mirror-gapping anomaly-free-gated + unproven) or an overclaim? Is "mass = the record gap when protection breaks" a genuine THEOREM on the unoriented branch -- W=eta*theta-log cosh eta=0.156109200157240, the three roles (spectral gap / lightest mass / event price) equal to <1e-40, the commitment cubic theta^3+theta^2+theta-1=0 -- and correctly ONLY a computable CONJECTURE on the oriented branch (collapse exact n=3 0.1335 / n=4 0.0645, n5/n6 sampled UBs, asymptotics open)? Is the paper careful NOT to claim a finished biconditional? Flag any blur between theorem-grade and conjecture-grade.'],
  ['PART B: THE MODE-CANONICALIZATION WALL (sec 4). RUN m2. Is the gauge-inequivalence diagnosis decisive -- are the ledger ranks [1,3,7] genuinely INVARIANT under record-internal gauge (no map changes them) => genuinely DISTINCT superselection sectors with non-identifiable coefficients 0.609/0.495/0.368? Do ALL THREE routes genuinely fail: Route 1 completeness (HORN A: maximal ledger pushes the coeff DOWN the dilution ladder AWAY from eta_B; HORN B: modes recorded-distinct D(P_etaB||P_h*)=0.00479>0 so dissolution does not apply); Route 2 external identity (xi=1/eta is the seal equation tanh eta=e^-eta rewritten, symbolic residual 0 = tautology; xi mode-covariant xi(h_*)=1.2814 != 1.6410; 1/eta_B weight-0 record-internal per Paper III); Route 3 variational (max-content -> eta_B vs completeness -> dilution limit OPPOSITE; firing clock E[I]=1 mode-blind; skewed base p=0.2 content 0.526 > W_*=0.365 => gate is the choice, extremum circular)? Is "fifth l_step-type wall, same shape as Paper III" faithful? Is "the sole escape (a matter Hamiltonian selecting one rank) RELOCATES the choice, never closes the wall" honest?'],
  ['OVERCLAIM HUNT BOTH directions + the gated conclusion + discipline (secs 1,5,6,7,8,9). (a) Does the paper REFUSE to predict any mass/ratio, AVOID a finished massless-iff biconditional, AVOID claiming the PSG group H1(SG,IGG) derived or the ledger-chirality<->Weyl-chirality bridge built, AVOID fixing the count N? Confirm each disavowal (secs 6-8). (b) Is the hierarchy correctly FORM-ONLY (sec 5: c_m smallness = 1/N mode-count ratio, Sakharov/Dvali isomorph, the count weight-0 + NOT corpus-forced ~37 orders short, one calibration survives = Paper V c_m=gamma_G*nu_m^2) -- and NOT smuggled into a value prediction? (c) Is "no single physical mass ratio computable now, doubly gated (the mode wall + the unbuilt chirality bridge + conjectural asymptotics)" honest and load-bearing (sec 6)? (d) Does it correctly CREDIT the synthesis + theorem-grade gap + fifth wall without under-stating? Is "synthesis-plus-no-go" the right overall framing? (e) Pre-geometric discipline: any continuum field / spinor bundle / mass scale smuggled as INPUT? Single-threaded? Do the references resolve and is the citation of Levin-Wen, Wen-PSG, Nielsen-Ninomiya, Ginsparg-Wilson, Wen-1305.1045, Sakharov-Dvali, and companion v6 papers 7/8/9/14/10 + Papers II/III/V faithful? Hunt any remaining overclaim or unfaithful citation.'],
].map(([f]) => () => agent(
  `Hostile, high-precision review of v7 Paper VIII (chiral fermions from record structure + the mode-canonicalization wall) at ${P8}. Your focus: ${f}\nRead the paper, the plan ${PLAN}, companion Papers III ${P3}, V ${P5}, and the v6 sources paper7 ${P7v6}, paper8 ${P8v6}, paper14 ${P14v6}. Run the receipts ${M1} , ${M2} + your own sympy/mpmath checks. ${RULES}\nReturn the schema.`,
  { label: `P8:${f.slice(0, 24)}`, phase: 'Review', schema: SCHEMA }
)))

return { reviews }
