#!/usr/bin/env python3
"""Round-2 opening O1/O2: normalized recurrent support process at dps=120.

The primitive clocks are independent Poisson processes in intrinsic support
evidence.  The auxiliary merge order is not retained; the physical object is
the marked trace partial order generated by shared lineage support.
"""

import itertools
import mpmath as mp

mp.mp.dps = 120
TOL = mp.mpf("1e-90")
checks = []


def check(label, ok, detail=""):
    checks.append(bool(ok))
    print(f"[{'PASS' if ok else 'FAIL'}] {label}" + (f" — {detail}" if detail else ""))


def infnorm(A):
    return max(abs(A[i, j]) for i in range(A.rows) for j in range(A.cols))


def kron(A, B):
    C = mp.zeros(A.rows * B.rows, A.cols * B.cols)
    for i in range(A.rows):
        for j in range(A.cols):
            for k in range(B.rows):
                for l in range(B.cols):
                    C[i * B.rows + k, j * B.cols + l] = A[i, j] * B[k, l]
    return C


print("[cg4 — normalized recurrent marked support process]")

# R0: the full recurrent count law is normalized by its probability generating function.
mus = [mp.mpf("0.37"), mp.mpf("0.61"), mp.mpf("0.29")]


def pgf(zs):
    return mp.exp(sum(mu * (z - 1) for mu, z in zip(mus, zs)))


norm = pgf([mp.mpf(1)] * len(mus))
means = []
for k in range(len(mus)):
    z = [mp.mpf(1)] * len(mus)
    # analytic first derivative at one for an independent Poisson coordinate
    means.append(mus[k] * pgf(z))
check("R0 normalized recurrent support-count law", abs(norm - 1) < TOL and means == mus,
      f"G(1)={mp.nstr(norm,8)}, means={[mp.nstr(x,6) for x in means]}")

# R1: strong-renewal identity after any finite past exposure.
past = [mp.mpf("0.11"), mp.mpf("2.7"), mp.mpf("9.2")]
increments = [mp.mpf("1e-30"), mp.mpf("0.4"), mp.mpf("3.1")]
renew_res = max(abs(mp.exp(-(p + d)) / mp.exp(-p) - mp.exp(-d))
                for p in past for d in increments)
# lineage 0 sees private support 0 plus shared support 01
dI0 = mus[0] + mus[2]
lineage_survival = mp.exp(-mus[0]) * mp.exp(-mus[2])
check("R1 stopping-history renewal and exact lineage marginal",
      renew_res < TOL and abs(lineage_survival - mp.exp(-dI0)) < TOL,
      f"renewal residual={mp.nstr(renew_res,8)}")

# R2: quotient gauge is not equality of raw race orders.
la, lb = mp.mpf("0.4"), mp.mpf("1.3")
p_ab = la / (la + lb)
p_ba = lb / (la + lb)
check("R2 unequal raw race orders push forward to one unordered outcome",
      abs(p_ab + p_ba - 1) < TOL and abs(p_ab - p_ba) > mp.mpf("0.1"),
      f"P(AB)={mp.nstr(p_ab,12)}, P(BA)={mp.nstr(p_ba,12)}, quotient=1")

# R3: physical locality is disjoint-union semigroup factorization, not next-event normalization.
QA = mp.matrix([[-la, mp.mpf(0)], [la, mp.mpf(0)]])
QB = mp.matrix([[-lb, mp.mpf(0)], [lb, mp.mpf(0)]])
I2 = mp.eye(2)
Qsum = kron(QA, I2) + kron(I2, QB)
t = mp.mpf("0.73")
factor_res = infnorm(mp.expm(t * Qsum) - kron(mp.expm(t * QA), mp.expm(t * QB)))
check("R3 disconnected-component semigroup factorization", factor_res < TOL,
      f"residual={mp.nstr(factor_res,8)}")

# R4: integrated local common-cause output kernel.
# h is written at the common ancestor.  Each party's local setting changes only
# its own noisy response to h.  Spin means factor: E[A_x B_y]=ax[x]*by[y].
ax = [mp.mpf("0.8"), mp.mpf("0.4")]
by = [mp.mpf("0.5"), mp.mpf("-0.25")]


def local_spin_prob(spin, h, mean):
    return (1 + spin * h * mean) / 2


def joint(aout, bout, xset, yset):
    return sum(mp.mpf("0.5") * local_spin_prob(aout, h, ax[xset])
               * local_spin_prob(bout, h, by[yset]) for h in (-1, 1))


norm_res = mp.mpf(0)
ns_a = mp.mpf(0)
ns_b = mp.mpf(0)
corr = {}
for x in (0, 1):
    for y in (0, 1):
        norm_res = max(norm_res, abs(sum(joint(a, b, x, y) for a in (-1, 1) for b in (-1, 1)) - 1))
        corr[x, y] = sum(a * b * joint(a, b, x, y) for a in (-1, 1) for b in (-1, 1))
for x in (0, 1):
    for a in (-1, 1):
        ns_a = max(ns_a, abs(sum(joint(a, b, x, 0) for b in (-1, 1))
                              - sum(joint(a, b, x, 1) for b in (-1, 1))))
for y in (0, 1):
    for b in (-1, 1):
        ns_b = max(ns_b, abs(sum(joint(a, b, 0, y) for a in (-1, 1))
                              - sum(joint(a, b, 1, y) for a in (-1, 1))))

# All CHSH signings with an odd number of minus signs.
chsh = []
for signs in itertools.product((-1, 1), repeat=4):
    if signs.count(-1) % 2 == 1:
        vals = [corr[0, 0], corr[0, 1], corr[1, 0], corr[1, 1]]
        chsh.append(abs(sum(s * v for s, v in zip(signs, vals))))
chsh_max = max(chsh)
check("R4 integrated two-sided no-signaling local-common-cause outcomes",
      norm_res < TOL and ns_a < TOL and ns_b < TOL and chsh_max <= 2,
      f"remote residuals={mp.nstr(ns_a,8)}/{mp.nstr(ns_b,8)}, CHSHmax={mp.nstr(chsh_max,8)}")

# R5: finite total support exposure gives finite Poisson mean, hence nonexplosion.
Lambda = sum(mus)
T = mp.mpf("12")
mean_events = Lambda * T
# Chernoff bound for N >= 100 is finite and tiny; existence of finite mean is load-bearing.
n = mp.mpf(100)
chernoff = mp.e ** (-mean_events) * (mp.e * mean_events / n) ** n
check("R5 finite-exposure nonexplosion certificate",
      mp.isfinite(mean_events) and chernoff < mp.mpf("1e-20"),
      f"mean={mp.nstr(mean_events,8)}, P(N>=100) bound={mp.nstr(chernoff,8)}")

print(f"CHECKS PASSED: {sum(checks)}/{len(checks)}")
raise SystemExit(0 if all(checks) else 1)

