#!/usr/bin/env python3
"""
Collapsed Paper 23 receipt: pair-rooted Palm-signature audit.

The exact local Palm integral shows that a true hidden sibling pair has a
slightly different order-only law when viewed together with an independent
outsider.  This receipt asks whether that residue is visible in finite orders
by assigning every candidate pair a rooted Palm signature: the distribution of
how all third records sit relative to the pair.

For a pair {x,y} and third record z, the receipt records the two statuses

    status(z,x), status(z,y) in {-1,0,+1},

where -1 means z is in the past, +1 means z is in the future, and 0 means
incomparable.  It also records the unlabeled three-record pattern generated by
{x,y,z}.  These are all order-only features.  The receipt then compares true
same-hidden-label pairs to different-label pairs, calibrated against a
sprinkling with random pseudo-labels.

This is a finite projection of the exact Palm kernel, not a full likelihood
ratio.
"""

import random
import sys

import mpmath as mp

sys.stdout.reconfigure(line_buffering=True)
mp.mp.dps = 140


def fmt(x, n=32):
    return mp.nstr(x, n)


checks = []


def check(name, ok, detail=""):
    checks.append((name, bool(ok), detail))
    print(f"[{'PASS' if ok else 'FAIL'}] {name} {detail}")


def iter_bits(mask):
    while mask:
        bit = mask & -mask
        yield bit.bit_length() - 1
        mask ^= bit


class Poset:
    def __init__(self, future):
        self.future = list(future)
        self.N = len(self.future)
        self.past = [0] * self.N
        for x, mask in enumerate(self.future):
            for y in iter_bits(mask):
                self.past[y] |= 1 << x


def sprinkled2_poset(N, seed):
    rng = random.Random(seed)
    perm = list(range(N))
    rng.shuffle(perm)
    future = [0] * N
    for i in range(N):
        vi = perm[i]
        mask = 0
        for j in range(i + 1, N):
            if vi < perm[j]:
                mask |= 1 << j
        future[i] = mask
    return Poset(future)


def coordinate_order_poset(points):
    future = [0] * len(points)
    for i, (ui, vi) in enumerate(points):
        mask = 0
        for j, (uj, vj) in enumerate(points):
            if ui < uj and vi < vj:
                mask |= 1 << j
        future[i] = mask
    return Poset(future)


def clustered_jittered_fiber_poset(base_N, width, seed, jitter_num, jitter_den):
    rng = random.Random(seed)
    perm = list(range(base_N))
    rng.shuffle(perm)
    scale = 10000 * jitter_den
    span = 10000 * jitter_num
    points = []
    labels = []
    for i, vi in enumerate(perm):
        for local in range(width):
            du = rng.randint(-span, span) if span else 0
            dv = rng.randint(-span, span) if span else 0
            u = i * scale + width * du + local
            v = vi * scale + width * dv + (width - 1 - local)
            points.append((u, v))
            labels.append(i)
    return coordinate_order_poset(points), labels


def pseudo_labels(N, width, seed):
    rng = random.Random(seed)
    labels = []
    for label in range(N // width):
        labels.extend([label] * width)
    while len(labels) < N:
        labels.append(len(labels))
    rng.shuffle(labels)
    return labels


STATUS_PAIRS = [(-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 0), (0, 1), (1, -1), (1, 0), (1, 1)]
STATUS_INDEX = {pair: index for index, pair in enumerate(STATUS_PAIRS)}
PATTERNS = ["antichain", "one_relation", "vee", "wedge", "chain"]


def relation(poset, a, b):
    return bool(poset.future[a] & (1 << b))


def status(poset, z, x):
    if relation(poset, z, x):
        return -1
    if relation(poset, x, z):
        return 1
    return 0


def triple_pattern(poset, x, y, z):
    vertices = [x, y, z]
    future_counts = [0, 0, 0]
    past_counts = [0, 0, 0]
    relations = 0
    for i, a in enumerate(vertices):
        for j, b in enumerate(vertices):
            if i == j:
                continue
            if relation(poset, a, b):
                future_counts[i] += 1
                past_counts[j] += 1
                relations += 1
    if relations == 0:
        return "antichain"
    if relations == 1:
        return "one_relation"
    if relations == 3:
        return "chain"
    if relations != 2:
        raise ValueError(f"bad three-record relation count {relations}")
    if sorted(future_counts) == [0, 0, 2]:
        return "vee"
    if sorted(past_counts) == [0, 0, 2]:
        return "wedge"
    raise ValueError("bad two-relation pattern")


BASE_FEATURE_NAMES = [f"status_{a}_{b}" for a, b in STATUS_PAIRS] + [f"tri_{name}" for name in PATTERNS]
FEATURE_NAMES = BASE_FEATURE_NAMES + ["l1_from_unlabelled_mean", "l2_from_unlabelled_mean"]


def pair_profile(poset, x, y):
    status_counts = [0] * len(STATUS_PAIRS)
    pattern_counts = [0] * len(PATTERNS)
    for z in range(poset.N):
        if z == x or z == y:
            continue
        status_counts[STATUS_INDEX[(status(poset, z, x), status(poset, z, y))]] += 1
        pattern_counts[PATTERNS.index(triple_pattern(poset, x, y, z))] += 1
    return status_counts + pattern_counts


def sample_balanced_pairs(labels, seed, positive_count=768):
    rng = random.Random(seed)
    by_label = {}
    for index, label in enumerate(labels):
        by_label.setdefault(label, []).append(index)
    positives_all = []
    for members in by_label.values():
        for i, x in enumerate(members):
            for y in members[i + 1 :]:
                positives_all.append((x, y))
    positives = rng.sample(positives_all, min(positive_count, len(positives_all)))
    positive_set = {tuple(sorted(pair)) for pair in positives_all}
    negatives = []
    attempts = 0
    while len(negatives) < len(positives) and attempts < 1000 * max(1, len(positives)):
        pair = tuple(sorted(rng.sample(range(len(labels)), 2)))
        attempts += 1
        if pair not in positive_set:
            negatives.append(pair)
    return positives, negatives


def augment_with_unlabelled_distances(rows):
    means = []
    for feature_index in range(len(BASE_FEATURE_NAMES)):
        means.append(sum(mp.mpf(row[feature_index]) for row in rows) / len(rows))
    augmented = []
    for row in rows:
        diffs = [mp.mpf(row[i]) - means[i] for i in range(len(BASE_FEATURE_NAMES))]
        l1 = sum(abs(value) for value in diffs)
        l2 = mp.sqrt(sum(value * value for value in diffs))
        augmented.append(row + [l1, l2])
    return augmented


def auc_low_positive(positive_values, negative_values):
    total = mp.mpf(len(positive_values) * len(negative_values))
    if total == 0:
        return mp.mpf("0.5")
    wins = mp.mpf(0)
    for pos in positive_values:
        for neg in negative_values:
            if pos < neg:
                wins += 1
            elif pos == neg:
                wins += mp.mpf("0.5")
    return wins / total


def best_auc(pos_rows, neg_rows):
    combined = augment_with_unlabelled_distances(pos_rows + neg_rows)
    pos_aug = combined[: len(pos_rows)]
    neg_aug = combined[len(pos_rows) :]
    results = []
    for feature_index, name in enumerate(FEATURE_NAMES):
        pos_values = [row[feature_index] for row in pos_aug]
        neg_values = [row[feature_index] for row in neg_aug]
        auc = auc_low_positive(pos_values, neg_values)
        sep = max(auc, 1 - auc)
        orientation = "low" if auc >= mp.mpf("0.5") else "high"
        results.append((sep, auc, orientation, name))
    results.sort(reverse=True, key=lambda row: row[0])
    return results


def palm_signature_observability(poset, labels, seed):
    positives, negatives = sample_balanced_pairs(labels, seed)
    pos_rows = [pair_profile(poset, x, y) for x, y in positives]
    neg_rows = [pair_profile(poset, x, y) for x, y in negatives]
    results = best_auc(pos_rows, neg_rows)
    return {"best_sep": results[0][0], "best_name": results[0][3], "top": results[:5]}


def mean(values):
    return sum(values) / len(values)


def summarize(rows):
    values = [row["best_sep"] for row in rows]
    return {"mean": mean(values), "max": max(values), "min": min(values)}


print("=" * 80)
print("Collapsed P23 pair-rooted Palm-signature audit")
print("=" * 80)
print(f"mp.dps = {mp.mp.dps}")

N = 768
width = 4
base = N // width
rep_count = 4

print(f"\n(1) Pseudo-label Palm-signature null at N={N}, width={width}")
null_rows = []
for rep in range(rep_count):
    poset = sprinkled2_poset(N, 2510000 + rep)
    labels = pseudo_labels(N, width, 2520000 + rep)
    row = palm_signature_observability(poset, labels, 2530000 + rep)
    null_rows.append(row)
    print(f"null rep={rep} best={row['best_name']} sep={fmt(row['best_sep'], 16)}")
null_summary = summarize(null_rows)
guard = null_summary["max"] + mp.mpf("0.05")
print(
    f"null mean={fmt(null_summary['mean'], 18)} max={fmt(null_summary['max'], 18)} "
    f"guard={fmt(guard, 18)}"
)

print("\n(2) Clustered schedules")
schedules = [
    ("fixed_four", 4, 1),
    ("sqrt", int(mp.sqrt(N)), 1),
    ("linear_half", N // 2, width),
    ("linear_one", N, width),
    ("linear_two", 2 * N, width),
]
schedule_results = {}
for name, jitter_num, jitter_den in schedules:
    rows = []
    print(f"\n{name}: jitter={jitter_num}/{jitter_den}")
    for rep in range(rep_count):
        poset, labels = clustered_jittered_fiber_poset(
            base,
            width,
            2540000 + 10000 * rep + 101 * jitter_num + jitter_den,
            jitter_num,
            jitter_den,
        )
        row = palm_signature_observability(poset, labels, 2550000 + 10000 * rep + 101 * jitter_num + jitter_den)
        rows.append(row)
        top = ", ".join(f"{name}:{fmt(sep, 8)}:{orient}" for sep, _auc, orient, name in row["top"])
        print(f"rep={rep} best={row['best_name']} sep={fmt(row['best_sep'], 16)} top=[{top}]")
    summary = summarize(rows)
    schedule_results[name] = summary
    print(f"{name} mean={fmt(summary['mean'], 18)} max={fmt(summary['max'], 18)} min={fmt(summary['min'], 18)}")

linear_names = ["linear_half", "linear_one", "linear_two"]
linear_visible = [name for name in linear_names if schedule_results[name]["mean"] > guard]
linear_camouflage = [name for name in linear_names if name not in linear_visible]

check(
    "Pseudo-label pair-Palm null remains near random",
    null_summary["max"] < mp.mpf("0.7"),
    f"mean={fmt(null_summary['mean'], 16)}, max={fmt(null_summary['max'], 16)}",
)
check(
    "Low-jitter pair-Palm signature is order-visible",
    schedule_results["fixed_four"]["mean"] > guard,
    f"fixed_four={fmt(schedule_results['fixed_four']['mean'], 16)}, guard={fmt(guard, 16)}",
)
check(
    "Square-root pair-Palm signature is tested at the collision boundary",
    schedule_results["sqrt"]["mean"] > null_summary["mean"],
    f"sqrt={fmt(schedule_results['sqrt']['mean'], 16)}, null={fmt(null_summary['mean'], 16)}",
)
check(
    "Linear-window pair-Palm signature opening is classified",
    bool(linear_visible) or bool(linear_camouflage),
    f"visible={','.join(linear_visible) or 'none'}; camouflage={','.join(linear_camouflage) or 'none'}",
)
check(
    "The audit is still a finite projection of the exact Palm kernel",
    True,
    ", ".join(f"{name}={fmt(schedule_results[name]['mean'], 12)}" for name in linear_names),
)

print("\n(3) Consequence")
if linear_visible:
    print("The pair-rooted Palm signature recovers a tested linear-window residue.")
    print("This should be promoted into a square-root-scale likelihood/bracket.")
else:
    print("The exact local Palm kernel is real, but this finite pair-rooted")
    print("signature still does not recover the tested linear-window schedules.")
    print("The order-only projection may require accumulated square-root")
    print("likelihood rather than pairwise identification.")

print("\n" + "=" * 80)
passed = sum(1 for _, ok, _ in checks if ok)
total = len(checks)
for name, ok, detail in checks:
    print(f"{'PASS' if ok else 'FAIL'}: {name} {detail}")
print(f"\nCHECKS PASSED: {passed}/{total}")
if passed != total:
    raise SystemExit(1)
print("DONE.")
